### ISSUE TITLE
Uploading Project to asset.party Fails

### ISSUE THREAD

**Issue by anthonysharpy** [Facepunch/sbox-issues#4233]
### Describe the bug

When I go to upload my project it always gets stuck on these files, even if I wait ages

![image](https://github.com/Facepunch/sbox-issues/assets/55365296/c1861cb3-c1de-45f5-92d6-1f59f51e6aaa)

### To Reproduce

Not sure. Maybe because they are large files?

### Expected behavior

upload works

### Additional context

Originally I was getting a "timeout after 100 seconds" error message (which was weird because the files didn't even take 100 seconds to upload), and then it did eventually create the project on asset.party (but... with no files in it). I tried deleting the project on asset.party and ever since then I just get this error:

```
2023/12/17 15:21:58.7543	[GameMenu] Invalid package	System.InvalidOperationException: Invalid package
   at Sandbox.Api.PostAsync(String url, Object values, Dictionary`2 headers, Callback progress, CancellationToken token)
   at Sandbox.Api.PostAsync[T](String url, Object values, Dictionary`2 headers, Callback progress, CancellationToken token)
   at Sandbox.Api.Packages.UploadFile.ExecAsync(Callback progress, CancellationToken token)
   at Sandbox.SandboxToolExtensions.UploadFile(Package package, Byte[] contents, String relativePath, Callback progress, CancellationToken token)
   at Sandbox.SandboxToolExtensions.UploadFile(Package package, String absolutePath, String relativePath, Callback progress, CancellationToken token)
   at Editor.ProjectSettingPages.PublishPage.UploadWizardPage.UploadFile(ProjectFile file, CancellationToken token) in C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\tools\code\Editor\ProjectSettings\Publish\PublishPage.3.UploadWizardPage.cs:line 213
   at Editor.ProjectSettingPages.PublishPage.UploadWizardPage.RunUploads() in C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\tools\code\Editor\ProjectSettings\Publish\PublishPage.3.UploadWizardPage.cs:line 192
   at Editor.ProjectSettingPages.PublishPage.UploadWizardPage.FinishAsync() in C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\tools\code\Editor\ProjectSettings\Publish\PublishPage.3.UploadWizardPage.cs:line 148
   at Editor.ProjectSettingPages.PublishPage.TrySwitchToNextPage() in C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\tools\code\Editor\ProjectSettings\Publish\PublishPage.cs:line 245
```

Project ID is lamerp.sandbox_city

**Comment by anthonysharpy** [comment]
Here's the timeout error I was getting

```
2023/12/17 14:56:03.5535	[GameMenu] The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.	System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
 ---> System.TimeoutException: The operation was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..
 ---> System.Net.Sockets.SocketException (995): The I/O operation has been aborted because of either a thread exit or an application request.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](Memory`1 buffer, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Sandbox.Api.<>c__DisplayClass32_1.<<PostAsync>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Sandbox.Api.PostAsync(String url, Object values, Dictionary`2 headers, Callback progress, CancellationToken token)
   at Sandbox.Api.PostAsync[T](String url, Object values, Dictionary`2 headers, Callback progress, CancellationToken token)
   at Sandbox.Api.Packages.UploadFile.ExecAsync(Callback progress, CancellationToken token)
   at Sandbox.SandboxToolExtensions.UploadFile(Package package, Byte[] contents, String relativePath, Callback progress, CancellationToken token)
   at Sandbox.SandboxToolExtensions.UploadFile(Package package, String absolutePath, String relativePath, Callback progress, CancellationToken token)
   at Editor.ProjectSettingPages.PublishPage.UploadWizardPage.UploadFile(ProjectFile file, CancellationToken token) in C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\tools\code\Editor\ProjectSettings\Publish\PublishPage.3.UploadWizardPage.cs:line 213
   at Editor.ProjectSettingPages.PublishPage.UploadWizardPage.RunUploads() in C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\tools\code\Editor\ProjectSettings\Publish\PublishPage.3.UploadWizardPage.cs:line 192
   at Editor.ProjectSettingPages.PublishPage.UploadWizardPage.FinishAsync() in C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\tools\code\Editor\ProjectSettings\Publish\PublishPage.3.UploadWizardPage.cs:line 148
   at Editor.ProjectSettingPages.PublishPage.TrySwitchToNextPage() in C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\tools\code\Editor\ProjectSettings\Publish\PublishPage.cs:line 245
```

**Comment by garrynewman** [comment]
Have you ever had problems with asset party before, in terms of browsing and downloading?

**Comment by anthonysharpy** [comment]
@garrynewman nah it's worked pretty good for about a year now, just seems to be ever since I've made this new project on the scene branch that it's acting up

**Comment by garrynewman** [comment]
During this process, is the editor freezing up, hanging? Or is there visible progress?

**Comment by anthonysharpy** [comment]
@garrynewman The frontend seems perfectly fine and it's responsive the whole time. If I had to take a guess I'd say it seems as if the asset.party API is tripping up and throwing an error when it receives/processes these files? Because these two big files seem to upload, but they never have their progress bars fill up completely whereas the other files do, almost like the API's not confirming completion or something. Then it's just stuck like this, but as I say the frontend is still responsive. Not only that but my project doesn't show up on asset.party at all when I look at my org. Maybe the project/org/files are somehow corrupt on the backend?

Seems like something that's probably a bit of a pain to debug. I can email my project files over or something if it's easier

![image](https://github.com/Facepunch/sbox-issues/assets/55365296/ae6129e1-7b5f-4d2a-a4ea-c4a0871293bf)

**Comment by anthonysharpy** [comment]
Oh okay so, if I go to my profile (https://asset.party/lamerp), my project doesn't show up, but if i manually type the URL in (https://asset.party/lamerp/sandbox_city) I can get to it 

![img](https://github.com/Facepunch/sbox-issues/assets/55365296/f060595e-1f3c-4aa5-9008-ab6c4a683b9a)

![image](https://github.com/Facepunch/sbox-issues/assets/55365296/aaccfa7f-fa79-44ba-93bc-b6667eec05d9)

To be fair, the project did somehow come up on asset.party the other day after a few failed attempts, but the files weren't uploading (same as now), so I deleted it to try and wipe any trace of it in case the project was corrupt on asset.party or something. 

Looking now it seems as if this just archived it as I can un-archive it... TBH would have expected it to automatically un-archive it when I attempted to upload the new project files to asset.party rather than remaining hidden

![image](https://github.com/Facepunch/sbox-issues/assets/55365296/5a0c5696-aeea-4821-bc90-3a360470eea0)

Bit strange as if you unarchive it, it does mostly say delete, not archive

![image](https://github.com/Facepunch/sbox-issues/assets/55365296/4269b426-a126-4424-b3d3-8d98f6ff5582)

Ok let me see if unarchiving it makes a difference.... 

Noope 😕 

![image](https://github.com/Facepunch/sbox-issues/assets/55365296/3e76578c-8121-4f35-adc5-ca8477ea1ad4)

**Comment by anthonysharpy** [comment]
Just thought I'd add that it fails even if uploading to a new project on a new organisation

**Comment by garrynewman** [comment]
I'm keeping an eye on the backend to see any errors that pop up, but nothing yet.

Can you take a look at your log file when it happens and let me know if there are any errors?

**Comment by anthonysharpy** [comment]
Ok so when I tried to upload it yesterday, there was one map file that was 7mb big (no compiled lightmaps) and another one that was 169mb

7mb one finished and got to the end, hung there for like 60 seconds, then disappeared, so that worked, even though it was a bit slow

169mb one got to the end, threw a HTTP timeout error, I waited 15 minutes, still stuck

So it seems the problem is big file -> too slow to process -> HTTP timeout ?

Maybe if I just send you the map you can see if the same happens on your end? I just did fast compile so this one is 125mb. Have confirmed that this one gets stuck as well.

https://drive.google.com/file/d/1p8Edglw1-RUYKHF_h0sdl-R-8Ma3DvMm/view?usp=drive_link

> Can you take a look at your log file when it happens and let me know if there are any errors?

There was nothing in the log files strangely, just this not very helpful line in the console. But I think my comment from a few weeks ago has the full stack trace.

![image](https://github.com/Facepunch/sbox-issues/assets/55365296/0a918ac9-0ce0-447b-8632-767748c73d82)

**Comment by garrynewman** [comment]
That should be enough for me to get it - thanks for taking the time to explain it

**Comment by garrynewman** [comment]
Okay I increased the timeout - it should cope a bit better now.

**Comment by anthonysharpy** [comment]
@garrynewman Slightly different error now but still seems to be failing

```
2024/01/20 18:03:25.2033	[GameMenu] Backend error - returned 524	System.InvalidOperationException: Backend error - returned 524
   at Sandbox.Api.PostAsync(String url, Object values, Dictionary`2 headers, Callback progress, CancellationToken token)
   at Sandbox.Api.PostAsync[T](String url, Object values, Dictionary`2 headers, Callback progress, CancellationToken token)
   at Sandbox.Api.Packages.UploadFile.ExecAsync(Callback progress, CancellationToken token)
   at Sandbox.SandboxToolExtensions.UploadFile(Package package, Byte[] contents, String relativePath, Callback progress, CancellationToken token)
   at Sandbox.SandboxToolExtensions.UploadFile(Package package, String absolutePath, String relativePath, Callback progress, CancellationToken token)
   at Editor.ProjectSettingPages.PublishPage.UploadWizardPage.UploadFile(ProjectFile file, CancellationToken token) in C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\tools\code\Editor\ProjectSettings\Publish\PublishPage.3.UploadWizardPage.cs:line 213
   at Editor.ProjectSettingPages.PublishPage.UploadWizardPage.RunUploads() in C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\tools\code\Editor\ProjectSettings\Publish\PublishPage.3.UploadWizardPage.cs:line 192
   at Editor.ProjectSettingPages.PublishPage.UploadWizardPage.FinishAsync() in C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\tools\code\Editor\ProjectSettings\Publish\PublishPage.3.UploadWizardPage.cs:line 148
   at Editor.ProjectSettingPages.PublishPage.TrySwitchToNextPage() in C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\tools\code\Editor\ProjectSettings\Publish\PublishPage.cs:line 245
```

**Comment by AfteraOfficiel** [comment]
I can't upload VPK

GameMenu Backend error - returned 524

![image](https://github.com/Facepunch/sbox-issues/assets/99672629/b00c1d1f-d944-4ad6-a213-aa704b4b080b)
