### ISSUE TITLE
`GameObject.Network.TakeOwnership();` throw `Error calling RPC (Parameter count mismatch.)`

### ISSUE THREAD

**Issue by PolSpock** [Facepunch/sbox-issues#4281]
### Describe the bug

Hello,

I recently tried to use `GameObject.Network.TakeOwnership()` for my game and i discovered that it will now throw an error on call.

### To Reproduce

1) Download https://github.com/Facepunch/sbox-scenestaging
2) Load `networking.scene`
3) Play & Connect another instance
4) Pick a wooden box with the Connected instance: it's gonna be called `TryPickup` and `go.Network.TakeOwnership();`
5) Look at the Host console: an error will be thrown:
```
Error calling RPC '-1616475703' on GameObject (Msg_TakeOwnership) (Parameter count mismatch.)
System.Exception: Error calling RPC '-1616475703' on GameObject (Msg_TakeOwnership) (Parameter count mismatch.)
   at Sandbox.Rpc.InvokeRpc(ObjectMessageMsg& message, TypeDescription& typeDesc, Object& targetObject, Connection& source)
   at Sandbox.Rpc.HandleIncoming(ObjectMessageMsg message, Connection source)
   at Sandbox.SceneNetworkSystem.OnObjectMessage(ObjectMessageMsg message, Connection source)
   at Sandbox.Network.NetworkSystem.<>c__DisplayClass72_0`1.<AddHandler>b__0(Object o, Connection channel)
   at Sandbox.Network.NetworkSystem.HandleIncomingMessage(NetworkMessage msg)
```

### Expected behavior

No error, so no network unsync issue

### Media/Files

https://github.com/Facepunch/sbox-issues/assets/5229571/bc1199cd-5d05-408d-92fa-08117b31d9ef

**Comment by garrynewman** [comment]
Something for @kurozael to look into I think.

**Comment by kurozael** [comment]
Sorted 👍
