### ISSUE TITLE
VideoPlayer.Play NullReferenceException every frame when playing a video in the UI

### ISSUE THREAD

**Issue by chrisspieler** [Facepunch/sbox-issues#4298]
### Describe the bug

Whenever using a video as the background-image of a URL, an NRE is logged every frame.
```
Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Sandbox.VideoPlayer.Play(BaseFileSystem filesystem, String path)
   at Sandbox.TextureLoader.VideoTextureLoader.Load(BaseFileSystem filesystem, String filename, Boolean warnOnMissing)
   at Sandbox.Texture.TryToLoad(BaseFileSystem filesystem, String filepath, Boolean warnOnMissing)
   at Sandbox.Texture.Load(BaseFileSystem filesystem, String filepath, Boolean warnOnMissing)
   at Sandbox.UI.Styles.<>c__DisplayClass84_0.<SetImage>b__0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location ---
   at System.Lazy`1.CreateValue()
   at Sandbox.UI.BaseStyles.get_BackgroundImage()
   at Sandbox.UI.PanelRenderer.ShouldDrawBackground(Panel panel)
   at Sandbox.UI.PanelRenderer.DrawBackground(Panel panel, RenderState& state)
   at Sandbox.UI.Panel.DrawBackground(PanelRenderer renderer, RenderState& state)
   at Sandbox.UI.PanelRenderer.Render(Panel panel, RenderState state)
   at Sandbox.UI.PanelRenderer.Render(Panel panel, RenderState state)
   at Sandbox.UI.PanelRenderer.Render(Panel panel, RenderState state)
   at Sandbox.UI.PanelRenderer.Render(RootPanel panel, Single opacity)
   at Sandbox.UI.RootPanel.Render(Single opacity)
   at Sandbox.UI.RootPanel.RenderManual(Single opacity)
   at Sandbox.ScreenPanel.Sandbox.Component.IRenderOverlay.OnRenderOverlay(SceneCamera camera)
   at Sandbox.Scene.OnRenderOverlayInternal(SceneCamera camera)
   at Sandbox.CameraComponent.OnCameraRenderOverlay(SceneCamera camera)
   at Sandbox.CameraComponent.<>c__DisplayClass58_0.<UpdateCamera>b__0()
   at Sandbox.SceneCamera.OnRenderStage(RenderStage renderStage)
   at Sandbox.Graphics.OnLayer(Int32 stageenum, ManagedRenderSetup_t setup)
   at Managed.SandboxEngine.Exports.Sandbox_Graphics_OnLayer(Int32 renderHookStage, ManagedRenderSetup_t setup)
```

### To Reproduce

1. Open the attached project in the editor
2. Open minimal.scene
3. On the VideoPanel component of the Screen GameObject, set VideoPath to "videos/test_video.mp4"
4. Play the scene
5. Observe the NREs appearing in console

### Expected behavior

The video should be displayed without any errors.

### Media/Files

Repro project:
[video_nre_repro.zip](https://github.com/Facepunch/sbox-issues/files/13757771/video_nre_repro.zip)
Video demonstrating the error:
https://github.com/Facepunch/sbox-issues/assets/8889285/53435fbf-8ad3-44f5-a99b-b30774107650

### Additional context

This issue also occurs on another project that was previously working several days ago, so it's likely that a recent change caused this issue.

**Comment by chrisspieler** [comment]
Thanks, this works now.
