### ISSUE TITLE
Have SCSS parser errors include which .razor/.scss files the error occurred in

### ISSUE THREAD

**Issue by dch-GH** [Facepunch/sbox-issues#4541]
### For?

S&Box

### What can't you do?

![image](https://github.com/Facepunch/sbox-issues/assets/66768086/0241849d-9664-4e85-95c0-3fac9144c5a9)
This is all very useless unless you ctrl+f or just know what file this happened in, such as if the error only happened after you edited a particular file. 

The worse offender is when you try to use a non-existing variable:
![image](https://github.com/Facepunch/sbox-issues/assets/66768086/091f5a5c-0292-4326-9fce-03ff16fa014b)
```
Error parsing stylesheet: Unknown Variable [/none:7]
   at Sandbox.UI.StyleParser.ReadStyleBlock(Parse& p, String selectors, StyleSheet sheet, StyleBlock parentNode)
   at Sandbox.UI.StyleParser.ReadStyleBlock(Parse& p, String selectors, StyleSheet sheet, StyleBlock parentNode)
   at Sandbox.UI.StyleParser.ParseToSheet(String content, String filename, StyleSheet sheet)
   at Sandbox.UI.StyleParser.ParseSheet(String content, String filename, IEnumerable`1 variables)
   at Sandbox.UI.StyleSheet.FromString(String styles, String filename, IEnumerable`1 variables)
System.Exception: Unknown Variable [/none:7]
   at Sandbox.UI.StyleParser.ReadStyleBlock(Parse& p, String selectors, StyleSheet sheet, StyleBlock parentNode)
   at Sandbox.UI.StyleParser.ReadStyleBlock(Parse& p, String selectors, StyleSheet sheet, StyleBlock parentNode)
   at Sandbox.UI.StyleParser.ParseToSheet(String content, String filename, StyleSheet sheet)
   at Sandbox.UI.StyleParser.ParseSheet(String content, String filename, IEnumerable`1 variables)
   at Sandbox.UI.StyleSheet.FromString(String styles, String filename, IEnumerable`1 variables)
```

### How would you like it to work?

Tell me what .razor/.scss file the error happened in, like how it works with C# errors.

### What have you tried?

crying

**Comment by xezno** [comment]
Added
