### ISSUE TITLE
Selecting .wav file in Asset Browser gives "QWidget was null when calling pos" error

### ISSUE THREAD

**Issue by ryleigh** [Facepunch/sbox-issues#4657]
https://github.com/Facepunch/sbox-issues/assets/1173137/6a96cea6-762d-4f15-9d44-b88edcea39b4

```
[Interop] QWidget was null when calling pos	System.NullReferenceException: QWidget was null when calling pos
   at Editor.Widget.get_Position()
   at Editor.Widget.set_Position(Vector2 value)
   at Editor.Inspectors.AssetPreviewWidget.DoLayout() in C:\Program Files (x86)\Steam\steamapps\common\Sandbox Game\addons\tools\code\Inspectors\AssetPreviewWidget.cs:line 103
   at Editor.Widget.InternalOnEvent(EventType e)
   at Managed.SourceTools.Exports.Editor_Widget_InternalOnEvent(UInt32 self, Int64 e)
```

**Comment by aylaylay** [comment]
Should be fixed now
