### ISSUE TITLE
InternalServerError when uploading a project

### ISSUE THREAD

**Issue by chrisspieler** [Facepunch/sbox-issues#4695]
### Describe the bug

Uploading my game to Asset Party fails. The console logs an error: `Backend error - returned InternalServerError`

A stack trace can be found in the attached log (I tried uploading a couple times):
```
2024/02/02 23:38:33.1079	[GameMenu] Project publish preparation failed for game	System.InvalidOperationException: Backend error - returned InternalServerError
   at Sandbox.Api.PostAsync(String url, Object values, Dictionary`2 headers, Callback progress, CancellationToken token)
   at Sandbox.Api.PostAsync[T](String url, Object values, Dictionary`2 headers, Callback progress, CancellationToken token)
   at Editor.EditorUtility.Projects.PublishAsset.ExecAsync(CancellationToken token)
   at Editor.ProjectPublisher.PrePublish(CancellationToken cancellationToken)
2024/02/02 23:38:33.1079	[GameMenu] Backend error - returned InternalServerError	System.InvalidOperationException: Backend error - returned InternalServerError
   at Editor.ProjectPublisher.PrePublish(CancellationToken cancellationToken)
   at Editor.ProjectSettingPages.PublishPage.UploadWizardPage.Refresh() in C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\tools\code\Editor\ProjectSettings\Publish\PublishPage.3.UploadWizardPage.cs:line 129
   at Editor.ProjectSettingPages.PublishPage.UploadWizardPage.OpenAsync() in C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\tools\code\Editor\ProjectSettings\Publish\PublishPage.3.UploadWizardPage.cs:line 51
   at Editor.ProjectSettingPages.PublishPage.SwitchCurrentPage() in C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\tools\code\Editor\ProjectSettings\Publish\PublishPage.cs:line 49
```

### To Reproduce

1. Import the project from the repo linked in Media/Files
2. Publish the project
3. Observe that at the File Uploads screen, an error is logged in the console.

### Expected behavior

There should be no error when uploading a project to Asset Party. Or if there is, the error message should be more clear.

### Media/Files

Project repo: https://github.com/chrisspieler/ducc_hunt_2
Log file: [Log.log](https://github.com/Facepunch/sbox-issues/files/14150470/Log.log)

**Comment by garrynewman** [comment]
I suspect one of your filenames contains ".." - I've updated the backend so it will give a nicer error when this happens.

**Comment by chrisspieler** [comment]
Thanks, I found the files with `..` and renamed them. There were some other files with square brackets that I think were also causing problems, so I took care of that too.
