### ISSUE TITLE
Using a resource type of `png` on a property results in `Unknown Resource` in inspector

### ISSUE THREAD

**Issue by trundlr** [Facepunch/sbox-issues#4756]
### Describe the bug

Using a `png` resource type for a property results in `Unknown Resource Resource` in the inspector. Jpg works fine, and you can even use pngs in their place.

Clicking on the `Unknown Resource Resource` button just triggers an error:
```
2024/02/11 17:35:00.4073	[Interop] Object reference not set to an instance of an object.	System.NullReferenceException: Object reference not set to an instance of an object.
   at Editor.AssetPicker.<>c.<.ctor>b__18_0(AssetType x) in C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\tools\code\Editor\AssetBrowser\AssetPicker.cs:line 47
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.String.Join(String separator, IEnumerable`1 values)
   at Editor.AssetPicker..ctor(Widget parent, List`1 assetTypes, Boolean showCloud) in C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\tools\code\Editor\AssetBrowser\AssetPicker.cs:line 47
   at Editor.ResourceStringControlWidget.OnMouseClick(MouseEvent e) in C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\tools\code\Widgets\ControlWidgets\ResourceStringControlWidget.cs:line 131
   at Editor.Widget.OnMouseReleased(MouseEvent e)
   at Editor.Widget.InternalMouseReleaseEvent(QMouseEvent e)
   at Managed.SourceTools.Exports.Editor_Widget_InternalMouseReleaseEvent(UInt32 self, IntPtr e)
```

![image](https://github.com/Facepunch/sbox-issues/assets/57276947/17110005-5248-4679-9f4f-a94b15daf210)

### To Reproduce

Set a property with attribute `ResourceType( "png" )` and observe the error

### Expected behavior

No error, can select png

**Comment by garrynewman** [comment]
Don't use `ResourceType` anymore, use `[ImageAssetPath]`

**Comment by trundlr** [comment]
This works, thanks. I will re-write the issue to specify deprecating ResourceType.
