### ISSUE TITLE
NullReferenceException when hover game view with no scene opened

### ISSUE THREAD

**Issue by GavrilovNI** [Facepunch/sbox-issues#4809]
### Describe the bug

i get
```
2024/02/16 00:28:05.1558	[Interop] Object reference not set to an instance of an object.	System.NullReferenceException: Object reference not set to an instance of an object.
   at Editor.NavMeshToolbarWidget.<>c.<Build>b__1_2() in C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\tools\code\Editor\HeaderBar\NavMeshToolbarWidget.cs:line 14
   at Editor.ToolbarGroup.<>c__DisplayClass3_0.<AddToggleButton>b__1() in C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\tools\code\Editor\HeaderBar\ToolbarGroup.cs:line 44
   at Editor.<ToolbarGroup>F7613242DAD4FA1D788D46F1122EC946FDFEBD0C27C653A786947E423EE0B64D3__EditorToolButton.OnPaint() in C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\tools\code\Editor\HeaderBar\ToolbarGroup.cs:line 115
   at Editor.Widget.InternalPaintEvent(QPainter e, Int32 flags)
   at Managed.SourceTools.Exports.Editor_Widget_InternalPaintEvent(UInt32 self, IntPtr e, Int32 flags)
   ```
   when hover game view with no opened scenes

### To Reproduce

close all scenes
put your mouse pointer in scene view

### Expected behavior

no exception is thrown

**Comment by GavrilovNI** [comment]
was fixed
