### ISSUE TITLE
Unhandled Type Sandbox.NetList

### ISSUE THREAD

**Issue by anthonysharpy** [Facepunch/sbox-issues#4839]
### Describe the bug

![image](https://github.com/Facepunch/sbox-issues/assets/55365296/dac7dd15-a521-421b-8430-33b5c0dff2ac)

### To Reproduce

Suspect this might be caused by putting a NetList inside a [Sync]ed struct.

### Expected behavior

Works

**Comment by anthonysharpy** [comment]
I think this is maybe also causing this error when connecting to the server.

```
2024/02/17 22:10:15.8662	[Generic] Index was outside the bounds of the array.	System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Sandbox.ByteStream.EnsureCanRead(Int32 size)
   at Sandbox.ByteStream.ReadByteStream(Int32 size)
   at Sandbox.NetworkTable.Read(ByteStream& reader)
   at Sandbox.NetworkObject.ReadDataTable(Byte[] data)
   at Sandbox.NetworkObject.OnUpdateMessage(ObjectUpdateMsg update)
   at Sandbox.NetworkObject..ctor(GameObject source, ObjectCreateMsg msg)
   at Sandbox.GameObject.NetworkSpawnRemote(ObjectCreateMsg msg)
   at Sandbox.SceneNetworkSystem.OnObjectCreate(ObjectCreateMsg message, Connection source)
   at Sandbox.SceneNetworkSystem.SetSnapshotAsync(SnapshotMsg msg)
   at Sandbox.Network.NetworkSystem.On_Handshake_Snapshot(SnapshotMsg snapshot, Connection source)
   at Sandbox.Network.NetworkSystem.<>c__DisplayClass77_1`1.<<AddHandler>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Sandbox.Network.NetworkSystem.ExceptionWrapAsync(Func`1 method)
2024/02/17 22:10:15.8662	[Generic] TODO - Disconnect, connection has crashed, remove it	
```

**Comment by kurozael** [comment]
You can't put a NetList in a struct. Structs should contain simple value types.

**Comment by garrynewman** [comment]
You can put a list or an array in a struct though, I think?

**Comment by kurozael** [comment]
I think you're right in that it will serialize with BytePacker. But in this case @anthonysharpy won't get any benefit from using NetList inside of a struct, and may as well just use a List or an array.

The bug here I think is that BytePacker doesn't recognize NetList and perhaps it should. But the usage of NetList here is still wrong.

**Comment by anthonysharpy** [comment]
Makes sense, so `List` and `Dictionary` will sync fine within a struct? I'm guessing it only supports lists and dictionaries of value types?

Might be something worth adding to the documentation as the documentation seems to imply that `List` and `Dictionary` are not supported, I think that's the only reason I was trying to use NetList.

**Comment by kurozael** [comment]
It will serialize them, yeah, but you should note that changes to the contents of those collections won't be synchronized. You can only synchronize changes to the contents of a collection if you use `NetList`, or `NetDictionary` directly with `[Sync]` as a component's property.

**Comment by anthonysharpy** [comment]
Makes sense 😄 Thank you

**Comment by garrynewman** [comment]
You're right - I don't think it should be able to serialize/deserialize NetlList or NetDictionary in a struct, and this is a non issue.
