### ISSUE TITLE
Exiting Play Mode will occasionally leave a Current Game scene behind

### ISSUE THREAD

**Issue by CarsonKompon** [Facepunch/sbox-issues#4855]
### Describe the bug

Sometimes when you exit play mode you'll get the following error in console and the Current Game scene will remain open:
![image](https://github.com/Facepunch/sbox-issues/assets/5159369/50c45450-1ab5-4763-ab10-91da47b255cd)

Attempting to enter Play Mode again afterwards will create another Current Game scene, but will be completely empty:
![image](https://github.com/Facepunch/sbox-issues/assets/5159369/1be87f1f-3b3b-49f1-ac21-13a8dee0400e)

Exiting Play Mode after this point will get rid of both Current Game scenes:
![image](https://github.com/Facepunch/sbox-issues/assets/5159369/5ebdea97-e174-4ca8-a9c4-3c9755ecf320)

### To Reproduce

Exit Play Mode while working on a project (presumably has something to do with networking? not really sure though)

### Expected behavior

Current Game scenes should never stick linger after exiting Play Mode

**Comment by trundlr** [comment]
```
2024/02/18 21:50:52.8228	[Interop] Assert: AreEqual 4 children weren't deleted!	System.Exception: Assert: AreEqual 4 children weren't deleted!
   at Sandbox.Diagnostics.Assert.AreEqual[T](T a, T b, String message)
   at Sandbox.GameObject.Clear()
   at Sandbox.Scene.Destroy()
   at Editor.EditorScene.Stop()
   at Editor.<PlayPause>FF0891029E40D9BF41C46BAF2994D23A4C1B926626571323F881561648ED387FE__PlayButton.OnMousePress(MouseEvent e) in C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\tools\code\Editor\HeaderBar\PlayPause.cs:line 64
   at Editor.Widget.InternalMousePressEvent(QMouseEvent e)
   at Managed.SourceTools.Exports.Editor_Widget_InternalMousePressEvent(UInt32 self, IntPtr e)
```

**Comment by CarsonKompon** [comment]
Was able to find some more info on this. We have a component that spawns other prefabs when it is destroyed (in OnDestroy). What happens is exiting play mode is firing OnDestroy when it isn't supposed to, causing new GameObjects to be created as it's trying to destroy them all (leading to an error)
