### ISSUE TITLE
Current Game fails to close properly with error

### ISSUE THREAD

**Issue by trundlr** [Facepunch/sbox-issues#4858]
### Describe the bug

Occasionally, closing the current game in the editor will result in an error:

```
2024/02/18 21:50:52.8228	[Interop] Assert: AreEqual 4 children weren't deleted!	System.Exception: Assert: AreEqual 4 children weren't deleted!
   at Sandbox.Diagnostics.Assert.AreEqual[T](T a, T b, String message)
   at Sandbox.GameObject.Clear()
   at Sandbox.Scene.Destroy()
   at Editor.EditorScene.Stop()
   at Editor.<PlayPause>FF0891029E40D9BF41C46BAF2994D23A4C1B926626571323F881561648ED387FE__PlayButton.OnMousePress(MouseEvent e) in C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\tools\code\Editor\HeaderBar\PlayPause.cs:line 64
   at Editor.Widget.InternalMousePressEvent(QMouseEvent e)
   at Managed.SourceTools.Exports.Editor_Widget_InternalMousePressEvent(UInt32 self, IntPtr e)
```

The CurrentGame remains open but is largely deconstructed (most gameobjects are destroyed).

### To Reproduce

Hard to reproduce since it happens so rarely. But typically just developing in the scene editor can cause this.

### Expected behavior

Current Game closes as expected.

### Media/Files

Will upload if I see it again, missed it first two times.

**Comment by trundlr** [comment]
Closing as duplicate of #4855
