### ISSUE TITLE
Testbed: networking scene is broken

### ISSUE THREAD

**Issue by ryleigh** [Facepunch/sbox-issues#4884]
Open Testbed project and start `networking.scene` in the editor.
Player model is broken and errors are spammed.

![sbox-dev_2024-02-19_16-03-49](https://github.com/Facepunch/sbox-issues/assets/1173137/739b33e7-6cd1-424f-be92-5ad9c8d1ab8f)

```
2024/02/19 16:03:27.9983	[GameMenu] OnEnabled on Sandbox.SphereCollider failed: keyframeBody should be null - OnDisabled wasn't called	System.Exception: keyframeBody should be null - OnDisabled wasn't called
   at Sandbox.Diagnostics.Assert.IsNull[T](T obj, String message)
   at Sandbox.Collider.OnEnabled()
   at Sandbox.CallbackBatch.Group.Execute()
2024/02/19 16:03:28.0340	[GameMenu] OnEnabled on Sandbox.SkinnedModelRenderer failed: Assert: _sceneObject should be null - disable wasn't called	System.Exception: Assert: _sceneObject should be null - disable wasn't called
   at Sandbox.Diagnostics.Assert.True(Boolean isValid, String message)
   at Sandbox.SkinnedModelRenderer.OnEnabled()
   at Sandbox.CallbackBatch.Group.Execute()
2024/02/19 16:03:28.0340	[GameMenu] OnEnabled on Sandbox.ModelRenderer failed: Assert: _sceneObject should be null - disable wasn't called	System.Exception: Assert: _sceneObject should be null - disable wasn't called
   at Sandbox.Diagnostics.Assert.True(Boolean isValid, String message)
   at Sandbox.ModelRenderer.OnEnabled()
   at Sandbox.CallbackBatch.Group.Execute()
2024/02/19 16:03:28.2375	[GameMenu] Exception when calling PreRender on Sandbox.WorldPanel: Object reference not set to an instance of an object.	System.NullReferenceException: Object reference not set to an instance of an object.
   at Sandbox.UI.WorldPanel.set_Transform(Transform value)
   at Sandbox.WorldPanel.OnPreRender()
   at Sandbox.Component.PreRender()
   at Sandbox.GameObject.<>c.<PreRender>b__59_0(Component c)
   at Sandbox.ComponentList.ForEach[T](String name, Boolean includeDisabled, Action`1 action)
```

**Comment by Nolankicks** [comment]
I should add a pull request to become apart of history.

**Comment by garrynewman** [comment]
Fixed
