### ISSUE TITLE
Error when Using Propety on List containing GameResource

### ISSUE THREAD

**Issue by B0zy** [Facepunch/sbox-issues#5047]
### Describe the bug

Doing the following 
```
[Property]
private List<GameResource> _CustomResource;
```
Will result in the following error message and also kill the Editors FPS
```
Error calling event 'tool.frame' on 'Editor.Inspectors.ComponentListWidget'
System.ArgumentNullException: Value cannot be null. (Parameter 'target')
   at System.ArgumentNullException.Throw(String paramName)
   at System.ArgumentNullException.ThrowIfNull(Object argument, String paramName)
   at Sandbox.Internal.TypeSerializedObject..ctor(Func`1 fetchTarget, TypeDescription typeDescription, SerializedProperty parent)
   at Sandbox.Internal.<TypeSerializedObject>F6ADCC74E15E321D185710A2190EAFBC1E7176321228DA37373D58BF36E214CAB__TypeSerializedField.TryGetAsObject(SerializedObject& obj)
   at Editor.ListControlWidget..ctor(SerializedProperty property) in D:\SteamLibrary\steamapps\common\sbox\addons\tools\code\Widgets\ControlWidgets\ListControlWidget.cs:line 19
   at InvokeStub_ListControlWidget..ctor(Object, Object, IntPtr*)
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

### To Reproduce

1. Make a new Component and add the following 
```
[Property]
private List<GameResource> _CustomResource;
```
2. Add Component to GameObject and errors appear with Fps being brought down to below 10

### Expected behavior

Should show a empty list that a user can enter GameResources into. It should also not lower the Editors FPS  ( FPS Stays down to 10 ish even after remove component )

**Comment by Game4Freak** [comment]
The [Property] attribute only works on actual c# properties.
Try this:
```
[Property]
private List<GameResource> _CustomResource { get; set; }
```

**Comment by B0zy** [comment]
> The [Property] attribute only works on actual c# properties. Try this:
> 
> ```
> [Property]
> public List<GameResource> _CustomResource { get; set; }
> ```

I tried it before and it errored but now it works after restarting my editor thanks

**Comment by DevulTj** [comment]
This was actually a bug, it shouldn't error out and break the inspector. I've fixed this so fields that are collections will work as intended now.
