### ISSUE TITLE
ActionGraph: Copy and paste errors

### ISSUE THREAD

**Issue by garrynewman** [Facepunch/sbox-issues#5128]
- Open editor
- Select all
- Copy
- Open other editor
- Paste
- Errors forever

```
2024/03/10 09:48:42.1635	[GameMenu] Paste is not valid json: System.NullReferenceException: Object reference not set to an instance of an object.
   at Facepunch.ActionGraphs.ValidationMessage.ValueNotAlwaysAvailable(Link context) in /home/runner/work/ActionGraphs/ActionGraphs/Facepunch.ActionGraphs/ActionGraph.Validation.cs:line 110
   at Facepunch.ActionGraphs.ActionGraph.CheckOutputDependencies(IReadOnlyList`1 sorted) in /home/runner/work/ActionGraphs/ActionGraphs/Facepunch.ActionGraphs/ActionGraph.Validation.cs:line 696
   at Facepunch.ActionGraphs.ActionGraph.Validate(Boolean force) in /home/runner/work/ActionGraphs/ActionGraphs/Facepunch.ActionGraphs/ActionGraph.Validation.cs:line 301
   at Facepunch.ActionGraphs.ActionGraph.DeserializeInsert(ActionGraphModel model, JsonSerializerOptions options, IReadOnlyDictionary`2& idRemap) in /home/runner/work/ActionGraphs/ActionGraphs/Facepunch.ActionGraphs/ActionGraph.Serialization.cs:line 539
   at Facepunch.ActionGraphs.ActionGraph.DeserializeInsert(String json, JsonSerializerOptions options) in /home/runner/work/ActionGraphs/ActionGraphs/Facepunch.ActionGraphs/ActionGraph.Serialization.cs:line 484
   at Editor.ActionGraphs.EditorActionGraph.DeserializeNodes(String serialized) in C:\git\sbox\game\editor\ActionGraph\EditorActionGraph.cs:line 204
   at Editor.NodeEditor.GraphView.PasteSelection() in C:\git\sbox\game\addons\tools\code\NodeGraph\GraphView.cs:line 281	
2024/03/10 09:48:42.1635	[ToolsDll] Error calling event 'tool.frame' on 'Editor.ActionGraphs.ErrorList'	System.NullReferenceException: Object reference not set to an instance of an object.
   at Facepunch.ActionGraphs.ValidationMessage.ValueNotAlwaysAvailable(Link context) in /home/runner/work/ActionGraphs/ActionGraphs/Facepunch.ActionGraphs/ActionGraph.Validation.cs:line 110
   at Facepunch.ActionGraphs.ActionGraph.CheckOutputDependencies(IReadOnlyList`1 sorted) in /home/runner/work/ActionGraphs/ActionGraphs/Facepunch.ActionGraphs/ActionGraph.Validation.cs:line 696
   at Facepunch.ActionGraphs.ActionGraph.Validate(Boolean force) in /home/runner/work/ActionGraphs/ActionGraphs/Facepunch.ActionGraphs/ActionGraph.Validation.cs:line 301
   at Facepunch.ActionGraphs.ActionGraph.get_Messages() in /home/runner/work/ActionGraphs/ActionGraphs/Facepunch.ActionGraphs/ActionGraph.Validation.cs:line 221
   at Editor.ActionGraphs.ErrorList.UpdateErrors() in C:\git\sbox\game\editor\ActionGraph\ErrorList.cs:line 110
   at Editor.ActionGraphs.ErrorList.Frame() in C:\git\sbox\game\editor\ActionGraph\ErrorList.cs:line 89
   at InvokeStub_ErrorList.Frame(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
2024/03/10 09:48:42.1635	[ToolsDll] Error calling event 'tool.frame' on 'Editor.ActionGraphs.MainWindow'	System.NullReferenceException: Object reference not set to an instance of an object.
   at Facepunch.ActionGraphs.ValidationMessage.ValueNotAlwaysAvailable(Link context) in /home/runner/work/ActionGraphs/ActionGraphs/Facepunch.ActionGraphs/ActionGraph.Validation.cs:line 110
   at Facepunch.ActionGraphs.ActionGraph.CheckOutputDependencies(IReadOnlyList`1 sorted) in /home/runner/work/ActionGraphs/ActionGraphs/Facepunch.ActionGraphs/ActionGraph.Validation.cs:line 696
   at Facepunch.ActionGraphs.ActionGraph.Validate(Boolean force) in /home/runner/work/ActionGraphs/ActionGraphs/Facepunch.ActionGraphs/ActionGraph.Validation.cs:line 301
   at Facepunch.ActionGraphs.ActionGraph.get_Messages() in /home/runner/work/ActionGraphs/ActionGraphs/Facepunch.ActionGraphs/ActionGraph.Validation.cs:line 221
   at Editor.ActionGraphs.EditorActionGraph.Update() in C:\git\sbox\game\editor\ActionGraph\EditorActionGraph.cs:line 362
   at Editor.ActionGraphs.MainWindow.Frame() in C:\git\sbox\game\editor\ActionGraph\MainWindow.cs:line 307
   at InvokeStub_MainWindow.Frame(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by Metapyziks** [comment]
I could repro it if the copied-from graph had an input parameter that the copied-to graph didn't have. For example, from an action in my old TriggerActionComponent into your new Collider.OnTriggerEnter action.

That should be fixed now, but maybe you found a different case?
