### ISSUE TITLE
"Expression Node can't return a Task"

### ISSUE THREAD

**Issue by yuberee** [Facepunch/sbox-issues#5157]
### Describe the bug

When attempting to add a new node in ActionGraph the error will pop up and the menu won't get populated. As far as I am aware there is no issue with the actiongraph themselves.

### To Reproduce

1. Open ActionGraph
2. Try to add a node
If you are unable to reproduce let me know and I'll make our repo public. (https://github.com/Small-Fish-Dev/Sauna/)
Already send an invite to @Metapyziks

### Expected behavior

.

### Media/Files

![image](https://github.com/Facepunch/sbox-issues/assets/59583743/ee02fdd9-ec24-4f0c-899d-55a9fb949496)
It also seems be deleting actiongraphs if I try to access them

### Additional context

```
Expression nodes can't return a Task.
System.Exception: Expression nodes can't return a Task.
   at Facepunch.ActionGraphs.Helpers.Assert(Boolean condition, String message)
   at Facepunch.ActionGraphs.NodeBinding.FromMethodBase(MethodBase method, NodeLibrary nodeLibrary)
   at Facepunch.ActionGraphs.MethodBinder.GetKnownOverloadInfo(MethodBase method)
   at System.Linq.Utilities.<>c__DisplayClass2_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToArray()
   at System.Linq.OrderedEnumerable`1.ToArray()
   at Facepunch.ActionGraphs.MethodBinder.Bind(BindingSurface surface)
   at Facepunch.ActionGraphs.MethodNodeDefinition.UpdateDefaultBinding()
   at Facepunch.ActionGraphs.MethodNodeDefinition.get_DefaultBinding()
   at Facepunch.ActionGraphs.MethodNodeDefinition.get_Attributes()
   at Editor.ActionGraphs.ActionGraphView.FindAllReflectionNodeTypes() in C:\Program Files (x86)\Steam\steamapps\common\sbox\editor\ActionGraph\ActionGraphView.cs:line 156
   at Editor.ActionGraphs.ActionGraphView.get_ReflectionNodeTypes() in C:\Program Files (x86)\Steam\steamapps\common\sbox\editor\ActionGraph\ActionGraphView.cs:line 34
   at Editor.ActionGraphs.ActionGraphView.GetExternalNodes()+MoveNext() in C:\Program Files (x86)\Steam\steamapps\common\sbox\editor\ActionGraph\ActionGraphView.cs:line 439
   at Editor.ActionGraphs.ActionGraphView.GetRelevantNodes()+MoveNext() in C:\Program Files (x86)\Steam\steamapps\common\sbox\editor\ActionGraph\ActionGraphView.cs:line 455
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at Editor.NodeEditor.GraphView.OnPopulateNodeMenu(Menu menu, Vector2 clickPos, PlugOut nodeOutput, String filter) in C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\tools\code\NodeGraph\GraphView.cs:line 452
   at Editor.NodeEditor.GraphView.PopulateNodeMenu(Menu menu, Vector2 clickPos, PlugOut nodeOutput, String filter) in C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\tools\code\NodeGraph\GraphView.cs:line 515
   at Editor.NodeEditor.GraphView.<>c__DisplayClass62_0.<CreateNodeMenu>b__0() in C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\tools\code\NodeGraph\GraphView.cs:line 581
   at Editor.Menu.OnAboutToShow()
   at Editor.QObject.<>c__DisplayClass12_0.<Callback>b__0()

```

**Comment by Metapyziks** [comment]
Pushed a fix, it should now log a warning and not break the node menu.

**Comment by yuberee** [comment]
Yup that fixed it, not sure why the BlackScreen node was Pure but it was amongst the first so I probably didn't understand what it meant.
Thanks!
