### ISSUE TITLE
The JSON value could not be converted to System.Guid

### ISSUE THREAD

**Issue by anthonysharpy** [Facepunch/sbox-issues#5181]
### Describe the bug

Sorry if this is something that's already known about but I started getting this error today which breaks the gamemode

```
2024/03/13 22:12:20.4193	[GameMenu] Exception when calling INetworkListener.OnActive	System.Text.Json.JsonException: The JSON value could not be converted to System.Guid. Path: $ | LineNumber: 0 | BytePositionInLine: 2.
 ---> System.FormatException: The JSON value is not in a supported Guid format.
   at System.Text.Json.ThrowHelper.ThrowFormatException(DataType dataType)
   at System.Text.Json.Serialization.Converters.GuidConverter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadNode[TValue](JsonNode node, JsonTypeInfo jsonTypeInfo)
   at Sandbox.Component.Deserialize(JsonObject node)
   at Sandbox.GameObject.DeserializeInternal(JsonObject node)
   at Sandbox.GameObject.InstantiatePrefab(PrefabFile prefabFile, CloneConfig& inst)
   at Sandbox.GameObject.Clone(CloneConfig& inst)
   at Sandbox.GameObject.Clone(Transform transform, GameObject parent, Boolean startEnabled, String name)
   at Sandbox.GameObject.Clone()
   at SandboxCity.RoleplayGameBase.CreatePlayer() in C:\Users\antho\Documents\s&box projects\sandbox_city\code\game\RoleplayGameBase.cs:line 123
   at SandboxCity.RoleplayGameBase.SpawnPlayer(Connection connection) in C:\Users\antho\Documents\s&box projects\sandbox_city\code\game\RoleplayGameBase.cs:line 105
   at SandboxCity.RoleplayGameBase.Sandbox.Component.INetworkListener.OnActive(Connection connection) in C:\Users\antho\Documents\s&box projects\sandbox_city\code\game\RoleplayGameBase.cs:line 51
   at Sandbox.SceneNetworkSystem.<>c__DisplayClass11_1.<OnJoined>b__0()
```

### To Reproduce

I donno if it's relevant but my player object has a component with:

```
[Sync, Property] public string ID { get; set; } = "";
```

### Expected behavior

No error

**Comment by anthonysharpy** [comment]
@kurozael cheers 😄 thanks for all the cool new networking updates lately 👍
