### ISSUE TITLE
Cannot open certain or first project on launcher

### ISSUE THREAD

**Issue by kodi022** [Facepunch/sbox-issues#5189]
### Describe the bug

Often and randomly I cannot open my first project on the editor launcher. This start just a day or two ago. Other projects seem to open fine. 

If relevant, I am trying to open the top (first & first pinned) project in the list, anything else opens fine.

### To Reproduce

I believe this to be the error, but I am not confident, the Log only prints this sometimes when the issue is happening.
```
2024/03/14 15:29:07.1296	[Bootstrap] A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.)	System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.set_Item(TKey key, TValue value)
   at Sandbox.Package.Cache(Package package, Boolean partial)
   at Sandbox.Package.FetchAsync(String identString, Boolean partial, Boolean useCache)
   at Sandbox.Package.FetchAsync(String identString, Boolean partial)
   at Sandbox.Package.Fetch(String identString, Boolean partial)
   at Editor.ProjectRow.UpdatePackageAsync() in C:\build\_work\sbox\sbox\engine\Launcher\StandaloneTest\Widgets\ProjectRow.cs:line 98
2024/03/14 15:29:07.1657	[Bootstrap] Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.	System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.set_Item(TKey key, TValue value)
   at Sandbox.Package.Cache(Package package, Boolean partial)
   at Sandbox.Package.FetchAsync(String identString, Boolean partial, Boolean useCache)
   at Sandbox.Package.FetchAsync(String identString, Boolean partial)
   at Sandbox.Package.Fetch(String identString, Boolean partial)
   at Editor.ProjectRow.UpdatePackageAsync() in C:\build\_work\sbox\sbox\engine\Launcher\StandaloneTest\Widgets\ProjectRow.cs:line 98
   ```

### Expected behavior

Can open any project

**Comment by kodi022** [comment]
This issue seems to not happen anymore for me, whether its fixed or not.
