### ISSUE TITLE
Setting the Value of a [Sync] Property Sometimes Throws an Error

### ISSUE THREAD

**Issue by anthonysharpy** [Facepunch/sbox-issues#5237]
### Describe the bug

I have a component called PlayerData where I stored all my... player data.

An example of a property in this component is:

```
[Sync, Property, SavedData] public float Health { get; set; }
```

SavedData is my own custom attribute that specifies that the data should be saved to disk (it uses a custom JSON converter but that's not really important).

This works great except for one thing.

This is a bit of an oversimplification but when loading data from disk, my JSON converter creates a new instance of the class (which in this case is a PlayerData component):

```
var instance = GlobalGameNamespace.TypeLibrary.Create( typeToConvert.Name, typeToConvert );
```

Looping through the SavedData properties, it attempts to set the values with the ones it loaded from disk:

```
property.SetValue( instance, value );
```

But doing so throws an error if it's a [Sync] property (in this stack trace it's trying to set a property called "UID"):

```
2024/03/19 21:22:39.4543	[GameMenu] Exception when calling 'FixedUpdate' on PersistenceManager:ServerGameController	System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Sandbox.Component.__sync_SetValue[T](WrappedPropertySet`1 p)
   at SandboxCity.PlayerData.set_UID(String value) in C:\Users\antho\Documents\s&box projects\sandbox_city\code\player\PlayerData.cs:line 21
   at InvokeStub_PlayerData.set_UID(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.InvokeOneParameter(Object obj, BindingFlags invokeAttr, Binder binder, Object parameter, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Reflection.PropertyInfo.SetValue(Object obj, Object value)
   at Sandbox.PropertyDescription.SetValue(Object obj, Object value)
   at DMD<System.Object NSSandbank.GenericSavedDataConverter:Read(System.Text.Json.Utf8JsonReader&, System.Type, System.Text.Json.JsonSerializerOptions)>(GenericSavedDataConverter this, Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCoreAsObject(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize(String json, Type returnType, JsonSerializerOptions options)
   at NSSandbank.Serialisation.DeserialiseClass(String data, Type type)
   at NSSandbank.Serialisation.CloneObject(Object theObject, Type objectType)
   at NSSandbank.Document..ctor(Object data, Type documentType, Boolean needsCloning)
   at Sandbank.Insert[T](String collection, T document)
   at SandboxCity.PlayerData.Save()
   at SandboxCity.PersistenceManager.<>c.<SaveWorld>b__2_0(PlayerData x)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at SandboxCity.PersistenceManager.SaveWorld()
   at SandboxCity.PersistenceManager.OnFixedUpdate()
   at Sandbox.Component.ExceptionWrap(String name, Action a)
```

I'm guessing it's freaking out because this is just a random instance of a Component class I made, and not something that's actually in the scene?

### To Reproduce

See above

### Expected behavior

Basically all I really want it to do here is not throw an error.

It's a bit difficult to justify what I think the behaviour should be without explaining what I'm trying to do...

I have a custom in-memory database that I made for s&box. It's a document model database, so the whole point of it is that someone can just say "take this class and save it to disk", and it will automagically serialise and deserialise the data. It generally doesn't/shouldn't matter what type the class is, so long as it has properties with the [SavedData] attribute.

The reason my player is storing its data on a component and not on something like a struct is because structs are inferior in a lot of ways. For starters, AFAIK structs don't support NetList and NetDictionary etc. Moreover, they're inefficient since the entire struct is re-networked, even if only a small part of it changes. So that's why PlayerData is a component specifically.

So the TLDR is that ideally I would like to a) use a component because it's good at networking, and b) store the data from PlayerData class component directly because it's the simplest option.

I could make some custom middle type like PlayerDataStored and then convert to and from it manually, storing that in the database instead:

```
PlayerData -> PlayerDataStored -> database -> PlayerDataStored -> PlayerData
```

But I think this is bad user experience. I want other people to be able to use this database too (when it's ready), and I don't want to have to force them to do stuff like that. Creating this intermediary object would also be a performance bottleneck.

There's a bunch of other reasons for me wanting to do this too so if there's any questions please ask :)

**Comment by kurozael** [comment]
To be clear, you're just essentially creating the component class without it being attached to a GameObject? I can see why this would error, Components aren't supposed to exist in this way. None the less, it isn't a difficult problem to solve in this _one_ case but you should be careful because there are going to be a lot of instances where GameObject will be `null`.

**Comment by anthonysharpy** [comment]
> To be clear, you're just essentially creating the component class without it being attached to a GameObject?

Yep this is pretty much it.

It's 100% fine if these don't actually work as real components, I just want the data from them really, so basically just need them to not error when the values are set. When I want to put the data into a real component I'll have some kind of helper method that transfers the data from the invalid component to the valid one.

Thanks 😁

**Comment by kurozael** [comment]
You should find this is fixed in the next build but let me know :)

**Comment by anthonysharpy** [comment]
@kurozael Sorry only just checked GitHub notifications, yep this works great thank you 😄
