### ISSUE TITLE
[ActionGraph] Cannot create nodes when graph embedded in GameResource

### ISSUE THREAD

**Issue by DrewBritt** [Facepunch/sbox-issues#5244]
### Describe the bug

When attempting to construct an ActionGraph embedded in a GameResource, creating a node fails and logs ```Json.NodeLibrary not set when deserializing, we need to be inside a Scene.Push() or Json.PushNodeLibrary() context.``` to the console. This worked up until very recently, as we use this functionality for Mission logic in Grug. However, I'm now noticing this error in my own project, and can confirm that the behavior now occurs in editor for Grug, too.

### To Reproduce

1. [Download repro](https://github.com/Facepunch/sbox-issues/files/14685679/agrepro.zip) and open test.scene
2. Observe that TestAction graph on Object -> TestComponent is able to be modified.
3. Observe that TestAction graph in TestResource.test GameResource cannot be modified, and logs an error in console when attempting to create a node.

### Expected behavior

ActionGraph behavior should be definable in GameResource context. As previously mentioned, we use this for Mission logic in Grug, but I'd also like to use this for defining gamemode state behavior and transition conditions independently from code in my own project.

### Media/Files

Stack trace for error logged:
```
[Interop] Json.NodeLibrary not set when deserializing, we need to be inside a Scene.Push() or Json.PushNodeLibrary() context.
   System.InvalidOperationException: Json.NodeLibrary not set when deserializing, we need to be inside a Scene.Push() or Json.PushNodeLibrary() context.
   at Sandbox.Json.<>c.<Initialize>b__6_0()
   at Facepunch.ActionGraphs.ExtendedJsonConverter`1.Write(Utf8JsonWriter writer, T value, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteCore[TValue](Utf8JsonWriter writer, TValue& value, JsonTypeInfo`1 jsonTypeInfo)
   at System.Text.Json.JsonSerializer.WriteString[TValue](TValue& value, JsonTypeInfo`1 jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Serialize[TValue](TValue value, JsonSerializerOptions options)
   at Editor.ActionGraphs.EditorActionGraph.Serialize() in F:\Games\SteamLibrary\steamapps\common\sbox\editor\ActionGraph\EditorActionGraph.cs:line 268
   at Editor.ActionGraphs.MainWindow.<.ctor>b__44_0() in F:\Games\SteamLibrary\steamapps\common\sbox\editor\ActionGraph\MainWindow.cs:line 220
   at Editor.ActionGraphs.UndoStack.Push(String name) in F:\Games\SteamLibrary\steamapps\common\sbox\editor\ActionGraph\UndoStack.cs:line 29
   at Editor.ActionGraphs.MainWindow.PushUndo(String name) in F:\Games\SteamLibrary\steamapps\common\sbox\editor\ActionGraph\MainWindow.cs:line 439
   at Editor.ActionGraphs.ActionGraphView.PushUndo(String name) in F:\Games\SteamLibrary\steamapps\common\sbox\editor\ActionGraph\ActionGraphView.cs:line 366
   at Editor.NodeEditor.GraphView.UndoScope(String name) in F:\Games\SteamLibrary\steamapps\common\sbox\addons\tools\code\NodeGraph\GraphView.cs:line 105
   at Editor.NodeEditor.GraphView.CreateNewNode(INodeType type, Vector2 position, PlugOut nodeOutput, Boolean selected) in F:\Games\SteamLibrary\steamapps\common\sbox\addons\tools\code\NodeGraph\GraphView.cs:line 657
   at Editor.NodeEditor.GraphView.<>c__DisplayClass58_0.<OnPopulateNodeMenu>b__1(INodeType type) in F:\Games\SteamLibrary\steamapps\common\sbox\addons\tools\code\NodeGraph\GraphView.cs:line 476
   at Editor.Menu.<>c__DisplayClass9_1`1.<BuildMenu>b__0()
   at Editor.Option.OnTriggered()
   at Editor.Option.InternalTriggered()
   at Managed.SourceTools.Exports.Editor_Option_InternalTriggered(UInt32 self)```

**Comment by Metapyziks** [comment]
Thanks for the report, fix should be building now.

**Comment by MrBrax** [comment]
i'm getting this in prefabs, are they considered gameresources too?

**Comment by MrBrax** [comment]
works now, getting some NRE's but i don't think it's related to this

**Comment by Metapyziks** [comment]
I'm happy to have a look if you think there's a chance it's a bug.

**Comment by MrBrax** [comment]
I'm getting these when right clicking in a new prefab action graph window and inserting a component node respectively:
```
Encountered 1 exception(s) when finding node types:
  System.String::Create: Expression nodes can't have signals.
   at Editor.ActionGraphs.ActionGraphView.FindAllReflectionNodeTypes() in C:\Program Files (x86)\Steam\steamapps\common\sbox\editor\ActionGraph\ActionGraphView.cs:line 288
   at Editor.ActionGraphs.ActionGraphView.get_ReflectionNodeTypes() in C:\Program Files (x86)\Steam\steamapps\common\sbox\editor\ActionGraph\ActionGraphView.cs:line 34
   at Editor.ActionGraphs.ActionGraphView.GetExternalNodes()+MoveNext() in C:\Program Files (x86)\Steam\steamapps\common\sbox\editor\ActionGraph\ActionGraphView.cs:line 454
   at Editor.ActionGraphs.ActionGraphView.GetRelevantNodes()+MoveNext() in C:\Program Files (x86)\Steam\steamapps\common\sbox\editor\ActionGraph\ActionGraphView.cs:line 470
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at Editor.NodeEditor.GraphView.OnPopulateNodeMenu(Menu menu, Vector2 clickPos, PlugOut nodeOutput, String filter) in C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\tools\code\NodeGraph\GraphView.cs:line 456
   at Editor.NodeEditor.GraphView.PopulateNodeMenu(Menu menu, Vector2 clickPos, PlugOut nodeOutput, String filter) in C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\tools\code\NodeGraph\GraphView.cs:line 519
   at Editor.NodeEditor.GraphView.<>c__DisplayClass63_0.<CreateNodeMenu>b__0() in C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\tools\code\NodeGraph\GraphView.cs:line 585
   at Editor.Menu.OnAboutToShow()
   at Editor.QObject.<>c__DisplayClass12_0.<Callback>b__0()
   at Editor.Menu.OpenAt(Vector2 position, Boolean modal)
   at Editor.NodeEditor.GraphView.OpenContextMenu(Vector2 pos, Vector2 clickPos, PlugOut nodeOutput) in C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\tools\code\NodeGraph\GraphView.cs:line 575
   at Editor.NodeEditor.GraphView.OnContextMenu(ContextMenuEvent e) in C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\tools\code\NodeGraph\GraphView.cs:line 400
   at Editor.Widget.InternalContextMenuEvent(QContextMenuEvent e)
   at Managed.SourceTools.Exports.Editor_GraphicsView_InternalContextMenuEvent(UInt32 self, IntPtr e)
   at Sandbox.EngineLoop.RunFrame(CMaterialSystem2AppSystemDict appDict, Boolean& wantsQuit)
   at Sandbox.AppSystem.RunFrame()
   at Sandbox.AppSystem.Run()
   at Sandbox.Launcher.Main() in C:\build\_work\sbox\sbox\engine\Launcher\SboxDev\Launcher.cs:line 24
   at Sandbox.Program.Launch() in C:\build\_work\sbox\sbox\engine\Launcher\Shared\Startup.cs:line 21
   at Sandbox.Program.Main() in C:\build\_work\sbox\sbox\engine\Launcher\Shared\Startup.cs:line 16
```

```
Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Facepunch.ActionGraphs.ActionGraph.AssertOwnership(LinkSource source)
   at Facepunch.ActionGraphs.ActionGraph.SetLink(Input target, LinkSource source)
   at Facepunch.ActionGraphs.Node.Input.SetLink(LinkSource source)
   at Editor.ActionGraphs.LocalInstanceNodeType.CreateNode(IGraph graph) in C:\Program Files (x86)\Steam\steamapps\common\sbox\editor\ActionGraph\ActionNodeType.cs:line 71
   at Editor.NodeEditor.GraphView.CreateNewNode(INodeType type, Action`1 onCreated) in C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\tools\code\NodeGraph\GraphView.cs:line 630
   at Editor.NodeEditor.GraphView.CreateNewNode(INodeType type, Vector2 position) in C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\tools\code\NodeGraph\GraphView.cs:line 621
   at Editor.NodeEditor.GraphView.CreateNewNode(INodeType type, Vector2 position, PlugOut nodeOutput, Boolean selected) in C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\tools\code\NodeGraph\GraphView.cs:line 659
   at Editor.NodeEditor.GraphView.<>c__DisplayClass58_0.<OnPopulateNodeMenu>b__1(INodeType type) in C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\tools\code\NodeGraph\GraphView.cs:line 476
   at Editor.Menu.<>c__DisplayClass9_1`1.<BuildMenu>b__0()
   at Editor.Option.OnTriggered()
   at Editor.Option.InternalTriggered()
   at Managed.SourceTools.Exports.Editor_Option_InternalTriggered(UInt32 self)
```

I have to close and reopen the action graph window for the node to start showing.

**Comment by Metapyziks** [comment]
The first one should be harmless (I'll fix it soon), the second one seems like a bug though. I'll open a new issue.
