### ISSUE TITLE
NRE when inserting a component node

### ISSUE THREAD

**Issue by Metapyziks** [Facepunch/sbox-issues#5253]
```
Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Facepunch.ActionGraphs.ActionGraph.AssertOwnership(LinkSource source)
   at Facepunch.ActionGraphs.ActionGraph.SetLink(Input target, LinkSource source)
   at Facepunch.ActionGraphs.Node.Input.SetLink(LinkSource source)
   at Editor.ActionGraphs.LocalInstanceNodeType.CreateNode(IGraph graph) in C:\Program Files (x86)\Steam\steamapps\common\sbox\editor\ActionGraph\ActionNodeType.cs:line 71
   at Editor.NodeEditor.GraphView.CreateNewNode(INodeType type, Action`1 onCreated) in C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\tools\code\NodeGraph\GraphView.cs:line 630
   at Editor.NodeEditor.GraphView.CreateNewNode(INodeType type, Vector2 position) in C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\tools\code\NodeGraph\GraphView.cs:line 621
   at Editor.NodeEditor.GraphView.CreateNewNode(INodeType type, Vector2 position, PlugOut nodeOutput, Boolean selected) in C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\tools\code\NodeGraph\GraphView.cs:line 659
   at Editor.NodeEditor.GraphView.<>c__DisplayClass58_0.<OnPopulateNodeMenu>b__1(INodeType type) in C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\tools\code\NodeGraph\GraphView.cs:line 476
   at Editor.Menu.<>c__DisplayClass9_1`1.<BuildMenu>b__0()
   at Editor.Option.OnTriggered()
   at Editor.Option.InternalTriggered()
   at Managed.SourceTools.Exports.Editor_Option_InternalTriggered(UInt32 self)
```

I have to close and reopen the action graph window for the node to start showing.

_Originally posted by @MrBrax in https://github.com/Facepunch/sbox-issues/issues/5244#issuecomment-2014891543_

**Comment by Metapyziks** [comment]
@MrBrax Can you repro this in an empty project? Is there something more specific I need to do than:

1. Create a new prefab
2. Add a component
3. Edit an action on that component
4. Create a node getting a component

**Comment by MrBrax** [comment]
I will try slicing it out, this is the local component code:

```csharp
public delegate bool IsTurnedOnDelegate();
	
[Property] public IsTurnedOnDelegate IsTurnedOn { get; set; }
```

**Comment by Metapyziks** [comment]
Aha that caused it to happen for me, thanks! Must be related to expression graphs.
