### ISSUE TITLE
Assets in library not present in the asset browser

### ISSUE THREAD

**Issue by ScoutWozniak** [Facepunch/sbox-issues#5417]
### Describe the bug

Assets present in a library's assets folder do not show in the asset browser, yet they are still there in file explorer.

### To Reproduce

Happens with the material present in the default library template.  Otherwise just create any file via the asset browser.

### Expected behavior

Assets should be shown there!

### Media/Files

Stack trace here, this happens only for file types from the Base Editor Library.  (FILEPATH is the actual file path, just censored it here)
```
Something went wrong when registering FILEPATH/StuffThatIsntBuiltIn/Assets/Materials/test.decal
   at Editor.AssetSystem.CreateResource(String type, String absoluteFilename)
   at Editor.CreateAsset.<>c__DisplayClass6_2.<AddOptions>b__2(String s) in C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\tools\Code\CreateAsset.cs:line 78
   at Editor.CreateAsset.<>c__DisplayClass6_3.<AddOptions>b__3() in C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\tools\Code\CreateAsset.cs:line 98
   at Editor.Option.OnTriggered()
   at Editor.Option.InternalTriggered()
   at Managed.SourceTools.Exports.Editor_Option_InternalTriggered(UInt32 self)
   at Editor.Menu.OpenAt(Vector2 position, Boolean modal)
   at Editor.AssetList.OpenFolderContextMenu(DirectoryInfo info, Boolean isThisFolder) in C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\tools\Code\Editor\AssetList\AssetList.ContextMenu.cs:line 523
   at Editor.AssetList.<.ctor>b__27_4() in C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\tools\Code\Editor\AssetList\AssetList.cs:line 127
   at Editor.BaseItemWidget.OnMousePress(MouseEvent e)
   at Editor.Widget.InternalMousePressEvent(QMouseEvent e)
   at Managed.SourceTools.Exports.Editor_BaseScrollWidget_InternalMousePressEvent(UInt32 self, IntPtr e)
   at Sandbox.EngineLoop.RunFrame(CMaterialSystem2AppSystemDict appDict, Boolean& wantsQuit)
   at Sandbox.AppSystem.RunFrame()
   at Sandbox.AppSystem.Run()
   at Sandbox.Launcher.Main() in C:\build\_work\sbox\sbox\engine\Launcher\SboxDev\Launcher.cs:line 24
   at Sandbox.Program.Launch() in C:\build\_work\sbox\sbox\engine\Launcher\Shared\Startup.cs:line 21
   at Sandbox.Program.Main() in C:\build\_work\sbox\sbox\engine\Launcher\Shared\Startup.cs:line 16
```

**Comment by ScoutWozniak** [comment]
Seems to be fixed now, thanks Garry!
