### ISSUE TITLE
Exception when calling 'Update' on PlayerController

### ISSUE THREAD

**Issue by kirillcarmaker** [Facepunch/sbox-issues#5429]
### Describe the bug

so i tried to play s&box for the first time and the player movement is broken

### To Reproduce

Exception when calling 'Update' on PlayerController on (Player - Kirill_Carmaker)

### Expected behavior

Work normaly like others do

**Comment by badandbest** [comment]
Is this a problem with s&box or a problem in a specific gamemode?

**Comment by kirillcarmaker** [comment]
> Is this a problem with s&box or a problem in a specific gamemode?

s&box

**Comment by PinkBunnyBun** [comment]
I'm also dealing with the same issue. This happens on any game mode I join in S&Box.

**Comment by UnknownDev37** [comment]
same

**Comment by handsomematt** [comment]
what is the exception https://docs.facepunch.com/s/sbox-dev/doc/reporting-errors-2OTPIafqCJ

**Comment by handsomematt** [comment]
exception from other issue

```
2024/04/29 22:31:51.4416	[GameMenu] Exception when calling 'FixedUpdate' on PlayerController on (Player - awd)	System.Exception: Default Surface not found!
   at Sandbox.Surface.FindByIndex(Int32 index)
   at Sandbox.PhysicsTraceResult.From(Result& result)
   at Sandbox.PhysicsTraceBuilder.GetResult()
   at Sandbox.PhysicsTraceBuilder.Run()
   at Sandbox.Scene.RunTrace(SceneTrace trace)
   at Sandbox.SceneTrace.Run()
   at Sandbox.CharacterController.TryUnstuck()
   at Sandbox.CharacterController.Move()
   at PlayerController.MovementInput() in PlayerController.cs:line 135
   at Sandbox.Component.ExceptionWrap(String name, Action a)
```
