### ISSUE TITLE
Missing Sky Texture Breaks Map Loading

### ISSUE THREAD

**Issue by anthonysharpy** [Facepunch/sbox-issues#5569]
### Describe the bug

Noticed today the map in my scene has suddenly broken and has no collision, this happened during the last week or so... think it's probably something to do with this error:

```
2024/05/26 00:05:18.1523	[GameMenu] Couldn't load map (Object reference not set to an instance of an object.)	System.NullReferenceException: Object reference not set to an instance of an object.
   at Sandbox.SkyBox2D.set_SkyMaterial(Material value)
   at Sandbox.SkyBox2D.InitializeFromLegacy(GameObject go, ObjectEntry kv)
   at Sandbox.<MapInstance>F631AF0934027528457158BC4F749E67F7F390AF8004976902BEF3BCFAD6CA188__MapComponentMapLoader.CreateObject(ObjectEntry kv)
   at Sandbox.MapLoader.CreateEntities(IWorldReference worldRef, String entityLumpName)
   at Sandbox.SceneMap.CreateEntities(String map, MapLoader loader)
   at Sandbox.SceneMap..ctor(SceneWorld sceneWorld, String map, MapLoader loader)
   at Sandbox.Map..ctor(String mapName, MapLoader loader)
   at Sandbox.MapInstance.LoadMapAsync(String mapName)
```

### To Reproduce

I can send over the map if needed

### Expected behavior

Works

**Comment by anthonysharpy** [comment]
Perhaps the issue is that I don't have a sky texture.......... maybe it was removed

**Comment by garrynewman** [comment]
Might be when we removed all the alyx stuff recently, either way this shouldn't be shitting itself like this.

**Comment by anthonysharpy** [comment]
Adding a new texture to the env_sky in Hammer and recompiling the map seems to fix it
