### ISSUE TITLE
After stop/playing a good amount of times (Editor), game server socket gets stuck open (?)

### ISSUE THREAD

**Issue by DevulTj** [Facepunch/sbox-issues#5589]
```Exception waiting for task to finish
System.Net.Sockets.SocketException (10048): Only one usage of each socket address (protocol/network address/port) is normally permitted.
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, Boolean disconnectOnFailure, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at System.Net.Sockets.TcpListener.Start(Int32 backlog)
   at Sandbox.Network.TcpSocket.SocketThread(String address, Int32 port, CancellationToken token)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Sandbox.Tasks.ExpirableSynchronizationContext.ProcessQueue()
```

**Comment by matekdev** [comment]
I seem to get this every single time I launch my game? I'm unable to do any local multiplayer development due to it.

**Comment by yuberee** [comment]
We get this everytime in our game: https://github.com/Small-Fish-Dev/deathcard/

**Comment by kurozael** [comment]
This should not happen anymore.
