### ISSUE TITLE
NRE on Networked object

### ISSUE THREAD

**Issue by yuberee** [Facepunch/sbox-issues#5596]
### Describe the bug

Having a networked object in the scene will return the following NRE:

```
Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Sandbox.NetworkObject.SendNetworkUpdate()
   at Sandbox.Scene.SceneNetworkUpdate()
   at Sandbox.Scene.GameTick()
   at Sandbox.Game.Frame()
   at Sandbox.GameMenu.GameMenuDll.Tick()
   at Sandbox.EngineLoop.FrameStart()
   at Sandbox.EngineLoop.RunFrame(CMaterialSystem2AppSystemDict appDict, Boolean& wantsQuit)
```

once every network tick (30 times a second by default)

### To Reproduce

1. Create scene
2. Add GameObject
3. Set the network mode to always
4. Run scene

**Comment by yuberee** [comment]
assigned @kurozael 1 minute ago

**Comment by aylaylay** [comment]
Fixed
