### ISSUE TITLE
[Action Graph] `An unhandled exception occurred, please report this.`

### ISSUE THREAD

**Issue by Nolankicks** [Facepunch/sbox-issues#5743]
### Describe the bug

When I added a pure attribute to a static method while the graph was still open, it gave me this error `An unhandled exception occurred, please report this.
System.Exception: Expression nodes must return a value.
   at Facepunch.ActionGraphs.Helpers.Assert(Boolean condition, String message)
   at Facepunch.ActionGraphs.NodeBinding.FromMethodBase(MethodBase method, NodeLibrary nodeLibrary)
   at Facepunch.ActionGraphs.MethodBinder.GetKnownOverloadInfo(MethodBase method)
   at System.Linq.Utilities.<>c__DisplayClass2_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToArray()
   at System.Linq.OrderedEnumerable`1.ToArray()
   at Facepunch.ActionGraphs.MethodBinder.Bind(BindingSurface surface)
   at Facepunch.ActionGraphs.MethodCallNodeDefinition.Bind(BindingSurface surface)
   at Facepunch.ActionGraphs.Node.UpdateParameters(Boolean keepMissing, List`1 outMessages)`

### To Reproduce

1. Create a static action graph method.
2. While you have it in the graph add the pure attribute.

### Expected behavior

My graph should not break and give this error.

### Additional context

The method is inside a static class.

**Comment by Metapyziks** [comment]
Does your method return void?

**Comment by Nolankicks** [comment]
@Metapyziks I think I was returning a tag set iirc.

**Comment by Metapyziks** [comment]
I could only reproduce with a pure method that returns void, so I've made the error a bit friendlier when you try to do that.

If you can still reproduce, could you send me the method you used? Thanks!
