### ISSUE TITLE
WebPanels don't allow local https with `-allowlocalhttp`

### ISSUE THREAD

**Issue by badandbest** [Facepunch/sbox-issues#5774]
### Describe the bug

I'm trying to display a WebPanel with a localhost url but it doesn't let me. Blocking local https is intentional, but the `-allowlocalhttp` launch paramter is supposed to allow you to bypass that.

This makes it so any time I want to see if a change works in-game I need to upload it instead of seeing it immediately.

### To Reproduce

1. Add `-allowlocalhttp` to Steam launch options.
2. Create a WebPanel.
3. Set WebPanel url to a loopback url.
4. InvalidOperationException.

### Expected behavior

`-allowlocalhttp` is supposed to let you bypass this restriction.

### Media/Files

```
Loopback urls are not allowed
   at Sandbox.WebSurface.OnStartRequest(HTML_StartRequest_t r)
   at Sandbox.WebSurface.<>c.<.cctor>b__9_1(HTML_StartRequest_t x)
   at Steamworks.Dispatch.<>c__DisplayClass10_0`1.<Install>b__0(IntPtr x)
   at Steamworks.Dispatch.ProcessCallback(CallbackType type, IntPtr data, Int32 dataSize, Boolean isServer)
   at Steamworks.Dispatch.OnClientCallback(Int32 type, IntPtr data, Int32 dataSize)
   at Managed.SandboxEngine.Exports.Steamworks_Dispatch_OnClientCallback(Int32 type, IntPtr data, Int32 datasize)
   at Sandbox.EngineLoop.FrameStart()
   at Sandbox.EngineLoop.RunFrame(CMaterialSystem2AppSystemDict appDict, Boolean& wantsQuit)
   at Sandbox.AppSystem.RunFrame()
   at Sandbox.AppSystem.Run()
   at Sandbox.Launcher.Main() in C:\build\_work\sbox\sbox\engine\Launcher\SboxDev\Launcher.cs:line 24
   at Sandbox.Program.Launch() in C:\build\_work\sbox\sbox\engine\Launcher\Shared\Startup.cs:line 21
   at Sandbox.Program.Main() in C:\build\_work\sbox\sbox\engine\Launcher\Shared\Startup.cs:line 16
```

**Comment by badandbest** [comment]
I checked again because the commit for #6380 mentioned removing a duplicate private url check?
![image](https://github.com/user-attachments/assets/c2562ee8-32ea-41f9-9069-a6c814d7c3a0)

But this is still an issue.

**Comment by handsomematt** [comment]
Made -allowlocalhttp work in editor for web surfaces, let me know if it works as expected. Won't be done for non editor

**Comment by badandbest** [comment]
I will check it out as soon as I get home

**Comment by badandbest** [comment]
I think -allowlocalhttp only working in the editor is a good call. You are very smart and handsome.
