### ISSUE TITLE
System.Exception Unhandled header 209 with new ByteStream

### ISSUE THREAD

**Issue by trundlr** [Facepunch/sbox-issues#5779]
### Describe the bug

Ever since the ByteStream re-write, we've been seeing some interesting exceptions from it. Usually they occur when starting a lobby, joining a lobby, etc. This error in particular is from Grodbert, who experienced it while already in a game of Grubs.

```
System.Exception: Unhandled header 209
   at Sandbox.BytePack.Deserialize(ByteStream& data)
   at Sandbox.BytePack.Packer.Deserialize(ByteStream& bs)
   at Sandbox.Internal.<Serializer>FF57C57C2BCD642D09194137E8656D202C3F93B60CFC1D3A0357B670E662E7B13__TypePacker`1.Read(ByteStream& bs)
   at Sandbox.BytePack.Deserialize(ByteStream& data)
   at Sandbox.BytePack.Packer.Deserialize(ByteStream& bs)
   at Sandbox.Internal.<Serializer>FF57C57C2BCD642D09194137E8656D202C3F93B60CFC1D3A0357B670E662E7B13__TypePacker`1.Read(ByteStream& bs)
   at Sandbox.BytePack.Deserialize(ByteStream& data)
   at Sandbox.BytePack.Packer.Deserialize(ByteStream& bs)
   at Sandbox.BytePack.ListPacker.Read(ByteStream& bs)
   at Sandbox.BytePack.Deserialize(ByteStream& data)
   at Sandbox.BytePack.Packer.Deserialize(ByteStream& bs)
   at Sandbox.Internal.<Serializer>FF57C57C2BCD642D09194137E8656D202C3F93B60CFC1D3A0357B670E662E7B13__TypePacker`1.Read(ByteStream& bs)
   at Sandbox.BytePack.Deserialize(ByteStream& data)
   at Sandbox.Internal.TypeLibrary.FromBytes[T](ByteStream& bs)
   at Sandbox.Network.NetworkSystem.HandleIncomingMessage(NetworkMessage msg)
   at Sandbox.Network.NetworkSystem.HandleIncomingMessage(NetworkMessage msg)
   at Sandbox.Network.SteamLobbySocket.GetIncomingMessages(MessageHandler handler)
   at Sandbox.Network.NetworkSystem.ProcessIncomingMessages()
   at Sandbox.Network.NetworkSystem.Tick()
   at Sandbox.Networking.Tick()
   at Sandbox.GameMenu.GameMenuDll.Tick()
   at Sandbox.EngineLoop.FrameStart()
   at Sandbox.EngineLoop.RunFrame(CMaterialSystem2AppSystemDict appDict, Boolean& wantsQuit)
```

### To Reproduce

Unknown

### Expected behavior

No ByteStream errors

**Comment by Metapyziks** [comment]
Some new entries got inserted into the BytePack.Identifier enum a couple hours before that error happened, which I think would explain this particular exception it if different clients had different versions running.

You mentioned having similar errors recently though, I guess before that enum change. Please keep the stack traces coming if they're still happening!

**Comment by trundlr** [comment]
Haven't seen anything - will re-open if it shows back up.
