### ISSUE TITLE
NRE in SceneNetworkSystem.OnJoined in the editor

### ISSUE THREAD

**Issue by trundlr** [Facepunch/sbox-issues#5780]
### Describe the bug

This error has been occurring occasionally when starting a game that has a NetworkHelper. There seem to be no special circumstances causing it from what we can tell. It is happening in Grubs, and hard to reproduce.

```
2024/07/03 18:32:06.6098	[Bootstrap] A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Object reference not set to an instance of an object.)	System.NullReferenceException: Object reference not set to an instance of an object.
   at Sandbox.SceneNetworkSystem.OnJoined(Connection client)
   at Sandbox.Network.NetworkSystem.InitializeGameSystem(Boolean host)
   at Sandbox.Network.NetworkSystem.InitializeHost()
   at Sandbox.Network.GameNetworkSystem.CreateLobbyAsync()
2024/07/03 18:32:06.6152	[Bootstrap] Object reference not set to an instance of an object.	System.NullReferenceException: Object reference not set to an instance of an object.
   at Sandbox.SceneNetworkSystem.OnJoined(Connection client)
   at Sandbox.Network.NetworkSystem.InitializeGameSystem(Boolean host)
   at Sandbox.Network.NetworkSystem.InitializeHost()
   at Sandbox.Network.GameNetworkSystem.CreateLobbyAsync()
```

### To Reproduce

Unknown

### Expected behavior

Lobby starts up successfully without error

**Comment by trundlr** [comment]
Haven't seen this since reporting initially.
