### ISSUE TITLE
Null ref exception on creating game after failing to create w/ compile error

### ISSUE THREAD

**Issue by cr4yz** [Facepunch/sbox-issues#58]
```
2021/04/28 11:57:16.985	Bootstrap	Object reference not set to an instance of an object.	System.NullReferenceException: Object reference not set to an instance of an object.
   at Sandbox.GameAssemblyManager.OnAssembly(String name, Stream dll, Stream pdb)
   at Sandbox.ServerInterface.OnAddonsCompiled(Compiler[] compiled)
   at Sandbox.ServerAddons.CompileAndHotloadAsync()
```

Reproduce: 

1. Sit in main menu, put an error in a gamemode's Game script (what I did: put IPhysicsUpdate without implementing the interface methods)
2. Try to create game with this gamemode, it will fail back to main menu.
3. Remove the error
4. Create game on the same gamemode, it will fail with above exception

You can mitigate the exception by creating a game on a different gamemode after step 2, seems to clean something up and makes it work.

**Comment by cr4yz** [comment]
I've noticed this exception still happens but it doesn't prevent a new game from being created like it did before.

Should this be closed?
