### ISSUE TITLE
Creating something new Models,Prefab etc. in Asset browser doesent work

### ISSUE THREAD

**Issue by EternalDawn1** [Facepunch/sbox-issues#5828]
### Describe the bug

Could not find file 'c:\users\dokumente\s&box projects\main\assets\models\'.
System.IO.FileNotFoundException: Could not find file ''.
File name: 'c:\users\\dokumente\s&box projects\vyndalium_main\sbox_vyndalium_main\vyndalium_main\assets\models\s'
   at System.IO.FileSystem.CreateDirectory(String fullPath, Byte[] securityDescriptor)
   at System.IO.DirectoryInfo.CreateSubdirectory(String path)
   at Editor.AssetList.<>c__DisplayClass15_0.<OnFolderContextMenu_BottomSection>b__3(String foldername) in R:\SteamLibrary\steamapps\common\sbox\addons\tools\Code\Editor\AssetList\AssetList.ContextMenu.cs:line 570
   at Editor.Dialog.TextDialog.Finish()
   at Editor.Button.OnClicked()
   at Editor.Button.InternalOnClicked()
   at Managed.SourceTools.Exports.Editor_Button_InternalOnClicked(UInt32 self)

### To Reproduce

.....

### Expected behavior

normally you can create assets , prefabs , models , out of FBX files , but its not working anymore , before it was working

**Comment by EternalDawn1** [comment]
https://github.com/user-attachments/assets/60024d01-605f-4952-9511-e253ff5110e6

**Comment by EternalDawn1** [comment]
got fixed by using a shorter direction
