### ISSUE TITLE
NRE on Component.get_Task() after game is closed / restarted 

### ISSUE THREAD

**Issue by trundlr** [Facepunch/sbox-issues#5834]
### Describe the bug

Using a Component's `TaskSource Task` will cause the game to error as shown below after Grubs has stopped or restarted:

```
A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Object reference not set to an instance of an object.)
System.NullReferenceException: Object reference not set to an instance of an object.
   at Sandbox.Component.get_Task()
   at Sandbox.Sdf.Sdf2DChunk.OnUpdateMeshAsync() in C:\Users\Aiden\Documents\S&box Projects\grubs\Libraries\facepunch.libsdf\Code\2D\Sdf2DChunk.cs:line 76
   at Sandbox.Sdf.SdfChunk`6.UpdateMesh() in C:\Users\Aiden\Documents\S&box Projects\grubs\Libraries\facepunch.libsdf\Code\SdfChunk.cs:line 183
   at Sandbox.TaskSource.WhenAll(Task[] tasks)
   at Sandbox.Sdf.SdfWorld`6.UpdateMesh(Layer layer) in C:\Users\Aiden\Documents\S&box Projects\grubs\Libraries\facepunch.libsdf\Code\SdfWorld.cs:line 768
   at Sandbox.TaskSource.WhenAll(IEnumerable`1 tasks)
   at Sandbox.Sdf.SdfWorld`6.ClearImpl() in C:\Users\Aiden\Documents\S&box Projects\grubs\Libraries\facepunch.libsdf\Code\SdfWorld.cs:line 383
   at Sandbox.Sdf.SdfWorld`6.ClearAsync() in C:\Users\Aiden\Documents\S&box Projects\grubs\Libraries\facepunch.libsdf\Code\SdfWorld.cs:line 369
```

Switching to System.Threading.Tasks.Task.CompletedTask seems to prevent this error.

### To Reproduce

1. Clone Grubs and open
2. Start and stop the game a few times. I found that hotloading, spinning up a second client, etc, can help reproduce the issue faster, but it may just be the placebo affect.
3. Notice ClearAsync and OnUpdateMeshAsync methods from SDF2DChunk failing when the Component.Task get is attempted.

### Expected behavior

There should be no errors when cleaning up these TaskSources

**Comment by Metapyziks** [comment]
I'll fix this in libsdf since it shouldn't be trying to access stuff on destroyed components.
