### ISSUE TITLE
The Sbox client fails to close games correctly though the pause menu.

### ISSUE THREAD

**Issue by MD485** [Facepunch/sbox-issues#5874]
### Describe the bug

Regardless of whether I click leave game or hold the escape button my game just freezes and refuses further input.

### To Reproduce

1. Start up a game.
2. Hit escape.
3. Hit leave game.
4. Freeze.
----------
2. Hold escape.
3. Freeze.

### Expected behavior

Not freezing.

### Media/Files

Log:
```
2024/07/21 02:09:29.0435	[Menu] Created Main Menu	
2024/07/21 02:09:36.2357	[Generic] Downloading 92 files (28.34mb)..	
2024/07/21 02:09:38.3223	[Generic] ..done in 2.09s	
2024/07/21 02:09:38.3301	[engine/ResourceSystem] Reloaded 3 resident symlinked resources in 1ms	
2024/07/21 02:09:39.9611	[GameMenu] 	
2024/07/21 02:09:40.0053	[Generic] Image.Load: /ui/tetros_effect_logo_glowing.png not found (Could not find file `/ui/tetros_effect_logo_glowing.png`.)	
2024/07/21 02:09:40.1477	[Generic] Couldn't find Input Action called "voice"	
2024/07/21 02:09:43.6493	[Generic] Object reference not set to an instance of an object.	System.NullReferenceException: Object reference not set to an instance of an object.
   at Sandbox.CookieContainer.Refresh()
   at Sandbox.CookieContainer.Save()
   at Sandbox.ConVarSystem.SaveAll()
   at Sandbox.GameMenu.GameMenuDll.Tick()
   at Sandbox.EngineLoop.FrameStart()
   at Sandbox.EngineLoop.RunFrame(CMaterialSystem2AppSystemDict appDict, Boolean& wantsQuit)
```

Then the null reference error continues repeating forever.

### Additional Information

Seems to happen regardless of game, I'm assuming it was a recent change to the engine internals.

**Comment by handsomematt** [comment]
@solwllms is this your recent change to CookieContainer

**Comment by solwllms** [comment]
Whoops, think I've caught this if you can give it another go @MD485, I've struggled to reliably repro.

**Comment by MD485** [comment]
LGTM
