### ISSUE TITLE
OverflowException in UploadWizard after publishing finishes in FileUsageWidget

### ISSUE THREAD

**Issue by trundlr** [Facepunch/sbox-issues#5892]
### Describe the bug

After publishing, I am seeing an OverflowException when navigating the wizard

```
Arithmetic operation resulted in an overflow.
System.OverflowException: Arithmetic operation resulted in an overflow.
   at System.Linq.Enumerable.Sum[TSource,TResult](IEnumerable`1 source)
   at Editor.ProjectSettingPages.FileUsageWidget.get_TotalUsage() in C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\tools\Code\Editor\ProjectSettings\Publish\PublishPage.3.UploadWizardPage.cs:line 270
   at Editor.ProjectSettingPages.FileUsageWidget.OnMouseMove(MouseEvent e) in C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\tools\Code\Editor\ProjectSettings\Publish\PublishPage.3.UploadWizardPage.cs:line 346
   at Editor.Widget.InternalMouseMoveEvent(QMouseEvent e)
   at Managed.SourceTools.Exports.Editor_Widget_InternalMouseMoveEvent(UInt32 self, IntPtr e)
```

### To Reproduce

Reproduction not consistent, but should be easy to fix

1. Go to publish a game
2. Have TotalUsage value sum to be greater than max int value
3. Observe error when publishing

### Expected behavior

No error should occur

**Comment by DevulTj** [comment]
Should be fine now
