### ISSUE TITLE
Clicking on the Network Mode in the inspector on a new prefab throws an error

### ISSUE THREAD

**Issue by Fortune117** [Facepunch/sbox-issues#5895]
### Describe the bug

Clicking on this button in the inspector throws an error on new prefabs
![image](https://github.com/user-attachments/assets/7085602f-569d-4314-a29c-ddd8263a5c3a)

### To Reproduce

1. Create a new prefab
2. Click on the button

### Expected behavior

Shouldn't throw an error

**Comment by DevulTj** [comment]
what's the error 😳

**Comment by Fortune117** [comment]
oop, sorry I meant to post it:
```CS
Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Editor.<GameObjectHeader>F737B676BC70F0A48B3C035DEDBC3C56626B92C4B533701E316989CF765AF8393__NetworkModeControlWidget.CreateOptionsWidget[T](SerializedProperty property, Action`1 onSelected, String customName) in C:\My Stuff\Steam\steamapps\common\sbox\addons\tools\Code\Scene\GameObjectInspector\GameObjectHeader.cs:line 452
   at Editor.<GameObjectHeader>F737B676BC70F0A48B3C035DEDBC3C56626B92C4B533701E316989CF765AF8393__NetworkModeControlWidget.OpenNetworkSettings() in C:\My Stuff\Steam\steamapps\common\sbox\addons\tools\Code\Scene\GameObjectInspector\GameObjectHeader.cs:line 364
   at Editor.<GameObjectHeader>F737B676BC70F0A48B3C035DEDBC3C56626B92C4B533701E316989CF765AF8393__NetworkModeControlWidget.OnMousePress(MouseEvent e) in C:\My Stuff\Steam\steamapps\common\sbox\addons\tools\Code\Scene\GameObjectInspector\GameObjectHeader.cs:line 286
   at Editor.Widget.InternalMousePressEvent(QMouseEvent e)
   at Managed.SourceTools.Exports.Editor_Widget_InternalMousePressEvent(UInt32 self, IntPtr e)

```

**Comment by DevulTj** [comment]
cheers lovely

**Comment by DevulTj** [comment]
Should be fine now
