### ISSUE TITLE
Maps only work once per session.

### ISSUE THREAD

**Issue by badandbest** [Facepunch/sbox-issues#5969]
### Describe the bug

When you try to load the same map more than once in a session it fails. This happens across every gamemode.

The only way to play the map again is to restart s&box.

### To Reproduce

1. In play mode, open any gamemode with a map.
2. Leave.
3. Open any gamemode with the same map.

s&box can't find the map.
```
2024/07/28 10:47:11.8647	[GameMenu] Couldn't load map (Unable to create world for map 'construct23')	System.Exception: Unable to create world for map 'construct23'
   at Sandbox.SceneMap.CreateWorld(SceneWorld sceneWorld, String map, Boolean async, Vector3 origin) in C:\build\_work\sbox\sbox\engine\Sandbox.Engine\SceneSystem\SceneMap.cs:line 124
   at Sandbox.SceneMap..ctor(SceneWorld sceneWorld, String map, MapLoader loader) in C:\build\_work\sbox\sbox\engine\Sandbox.Engine\SceneSystem\SceneMap.cs:line 76
   at Sandbox.MapInstance.LoadMapAsync(String mapName) in C:\build\_work\sbox\sbox\engine\Sandbox.Game\Scene\Components\Map\MapInstance.cs:line 280
```

### Expected behavior

Maps should load consistently.

### Media/Files

https://github.com/user-attachments/assets/f3cbecda-13ff-49ab-885a-7613fa222046

From other's perspective you fall through the world.

https://github.com/user-attachments/assets/38a1239b-fddf-41ab-ab5d-275cef4ed2a6

**Comment by aylaylay** [comment]
@garrynewman maps don't seem to get symlinked again after the first time the map is downloaded

**Comment by aylaylay** [comment]
This should be working now

**Comment by badandbest** [comment]
It works for me now 👍
