### ISSUE TITLE
Prefab variables UI not showing up in the Inspector if a Prefab Variable is not starred.

### ISSUE THREAD

**Issue by sol-vin** [Facepunch/sbox-issues#6116]
### Describe the bug

Prefab variables are not showing up even when starred in the Prefab Editor. This is because some part of the UI is crashing. This happens because a Prefab Variable was created but never linked to a Property. There is no way to delete a Prefab Variable currently.

### To Reproduce
Create a  2 prefab variables and then unstar one. Prefab variable window will be gone

### Expected behavior

Show the Prefab Variable window or allow deleteion of Prefab Variables.

### Media/Files

Error 1
```
Error calling event 'tool.frame' on 'Editor.PrefabVariablesWidget' (Object reference not set to an instance of an object.)
System.NullReferenceException: Object reference not set to an instance of an object.
   at Sandbox.SerializedProperty.Proxy.get_PropertyType() in C:\build\_work\sbox\sbox\engine\Sandbox.System\SerializedObject\SerializedProperty.cs:line 360
   at Editor.ControlWidget.Create(SerializedProperty property) in C:\build\_work\sbox\sbox\engine\Sandbox.Tools\ControlWidget\ControlWidget.cs:line 174
   at Editor.PrefabVariableWidget..ctor(PrefabVariable variable, VariableCollection collection) in C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\tools\Code\Scene\SceneTree\PrefabVariable\PrefabVariablesWidget.cs:line 127
   at Editor.PrefabVariablesWidget.UpdateTree() in C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\tools\Code\Scene\SceneTree\PrefabVariable\PrefabVariablesWidget.cs:line 70
   at Editor.PrefabVariablesWidget.Frame() in C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\tools\Code\Scene\SceneTree\PrefabVariable\PrefabVariablesWidget.cs:line 99
   at InvokeStub_PrefabVariablesWidget.Frame(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)

```

Error 2 
```
Error calling event 'tool.frame' on 'Editor.SceneTreeWidget' (Object reference not set to an instance of an object.)
System.NullReferenceException: Object reference not set to an instance of an object.
   at Sandbox.SerializedProperty.Proxy.get_PropertyType() in C:\build\_work\sbox\sbox\engine\Sandbox.System\SerializedObject\SerializedProperty.cs:line 360
   at Editor.ControlWidget.Create(SerializedProperty property) in C:\build\_work\sbox\sbox\engine\Sandbox.Tools\ControlWidget\ControlWidget.cs:line 174
   at Editor.PrefabVariableWidget..ctor(PrefabVariable variable, VariableCollection collection) in C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\tools\Code\Scene\SceneTree\PrefabVariable\PrefabVariablesWidget.cs:line 127
   at Editor.PrefabVariablesWidget.UpdateTree() in C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\tools\Code\Scene\SceneTree\PrefabVariable\PrefabVariablesWidget.cs:line 70
   at Editor.PrefabVariablesWidget.SetPrefab(PrefabScene prefab) in C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\tools\Code\Scene\SceneTree\PrefabVariable\PrefabVariablesWidget.cs:line 39
   at Editor.SceneTreeWidget.CheckForChanges() in C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\tools\Code\Scene\SceneTree\SceneTree.cs:line 171
   at InvokeStub_SceneTreeWidget.CheckForChanges(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

Error when clicking on a Prefab in a Scene.
```
ControlGroupWidget: Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Sandbox.SerializedProperty.Proxy.GetAttributes() in C:\build\_work\sbox\sbox\engine\Sandbox.System\SerializedObject\SerializedProperty.cs:line 370
   at Sandbox.SerializedProperty.GetAttributes[T]() in C:\build\_work\sbox\sbox\engine\Sandbox.System\SerializedObject\SerializedProperty.cs:line 101
   at Sandbox.SerializedProperty.HasAttribute[T]() in C:\build\_work\sbox\sbox\engine\Sandbox.System\SerializedObject\SerializedProperty.cs:line 76
   at Editor.<ControlSheet>F586CA1B6ACD304A24320B099358959EA48CB293482A2E7F407A0F7FA641BC8A8__ControlGroupWidget.<>c__DisplayClass1_0.<.ctor>b__0(SerializedProperty x) in C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\tools\Code\Editor\ControlSheet.cs:line 262
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Editor.<ControlSheet>F586CA1B6ACD304A24320B099358959EA48CB293482A2E7F407A0F7FA641BC8A8__ControlGroupWidget..ctor(String groupName, SerializedProperty[] props, Dictionary`2 collectControls) in C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\tools\Code\Editor\ControlSheet.cs:line 262
   at Editor.ControlSheet.AddGroup(String groupName, SerializedProperty[] props) in C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\tools\Code\Editor\ControlSheet.cs:line 65
```

### Additional context

Windows 10
nVidia 980
Driver 560.70

**Comment by MrBrax** [comment]
Happens when an unsupported variable type or attribute has been added to it. Happens to [Button]

<img width="388" alt="1722690912506" src="https://github.com/user-attachments/assets/8e07e896-ca45-4712-bf28-2cc9ba059aee">
<img width="384" alt="1722690747368" src="https://github.com/user-attachments/assets/76ffeb93-2399-4eb6-bb99-dfd68fcc5b58">
