### ISSUE TITLE
Opening asset browser causes the game to spit errors and crashes

### ISSUE THREAD

**Issue by Nolankicks** [Facepunch/sbox-issues#6243]
### Describe the bug

When opening the asset browser the game spits errors (Shown below)

### To Reproduce

1. Open a project.
2. Open the asset browser, see the crash.

### Expected behavior

No crash should happen.

### Media/Files

Error: ERROR: Reentrant call to CResourceSystem::BlockUntilManifestLoaded() while already in a frame update!
   at Sandbox.EngineLoop.Print(Int32 severity, String logger, String message) in C:\build\_work\sbox\sbox\engine\Sandbox.Engine\EngineLoop.cs:line 340
   at Managed.SandboxEngine.Exports.Sandbox_EngineLoop_Print(Int32 severitty, IntPtr logger, IntPtr message) in C:\build\_work\sbox\sbox\engine\Sandbox.Engine\Interop.Engine.cs:line 11540
   at Sandbox.Material.Create(String materialName, String shader) in C:\build\_work\sbox\sbox\engine\Sandbox.Engine\Resources\Material\Material.cs:line 31
   at Sandbox.Material.FromShader(String path) in C:\build\_work\sbox\sbox\engine\Sandbox.Engine\Resources\Material\Material.cs:line 68
   at Sandbox.SceneLineObject..ctor(SceneWorld sceneWorld) in C:\build\_work\sbox\sbox\engine\Sandbox.Engine\SceneSystem\SceneLineObject.cs:line 57
   at Sandbox.SceneTrailObject..ctor(SceneWorld sceneWorld) in C:\build\_work\sbox\sbox\engine\Sandbox.Engine\SceneSystem\SceneTrailObject.cs:line 48
   at Sandbox.ParticleTrail.OnEnabled(Particle p) in C:\build\_work\sbox\sbox\engine\Sandbox.Game\Scene\Components\Particles\Renderers\ParticleTrailRenderer.cs:line 123
   at Sandbox.ParticleEffect.UpdateParticle(Int32 index) in C:\build\_work\sbox\sbox\engine\Sandbox.Game\Scene\Components\Particles\ParticleEffect.cs:line 364
   at Sandbox.ParticleGameSystem.ProcessWork(ParticleWork work) in C:\build\_work\sbox\sbox\engine\Sandbox.Game\Scene\Components\Particles\ParticleGameSystem.cs:line 57
   at System.Threading.Tasks.Parallel.<>c__DisplayClass33_0`2.<ForEachWorker>b__0(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.Tasks.ThreadPoolTaskScheduler.TryExecuteTaskInline(Task task, Boolean taskWasPreviouslyQueued)
   at System.Threading.Tasks.TaskScheduler.TryRunInline(Task task, Boolean taskWasPreviouslyQueued)
   at System.Threading.Tasks.Task.InternalRunSynchronously(TaskScheduler scheduler, Boolean waitForCompletion)
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at Sandbox.ParticleGameSystem.UpdateParticles() in C:\build\_work\sbox\sbox\engine\Sandbox.Game\Scene\Components\Particles\ParticleGameSystem.cs:line 37
   at Sandbox.TimedCallbackList.CallbackEntry.Run() in C:\build\_work\sbox\sbox\engine\Sandbox.Game\Scene\GameObjectSystem\TimedCallbackList.cs:line 101
   at Sandbox.TimedCallbackList.Run() in C:\build\_work\sbox\sbox\engine\Sandbox.Game\Scene\GameObjectSystem\TimedCallbackList.cs:line 46
   at Sandbox.Scene.Signal(Stage stage) in C:\build\_work\sbox\sbox\engine\Sandbox.Game\Scene\Scene\Scene.System.cs:line 53
   at Sandbox.Scene.SharedTick() in C:\build\_work\sbox\sbox\engine\Sandbox.Game\Scene\Scene\Scene.Tick.cs:line 198
   at Sandbox.Scene.EditorTick(Single timeNow, Single timeDelta) in C:\build\_work\sbox\sbox\engine\Sandbox.Game\Scene\Scene\Scene.Tick.cs:line 104
   at Editor.Assets.PreviewPrefab.UpdateScene(Single cycle, Single timeStep) in C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\tools\Code\Assets\PreviewPrefab.cs:line 73
   at Editor.Assets.AssetPreview.RenderAssetThumbnail(Asset asset) in C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\tools\Code\Assets\AssetPreview.cs:line 182
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Editor.Assets.AssetPreview.RenderAssetThumbnail(Asset asset)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Sandbox.MethodDescription.InvokeWithReturn[T](Object targetObject, Object[] parameters) in C:\build\_work\sbox\sbox\engine\Sandbox.Reflection\TypeLibrary\Members\MethodDescription.cs:line 103
   at Editor.AssetThumbnail.RenderAssetThumb(Asset asset) in C:\build\_work\sbox\sbox\engine\Sandbox.Tools\Assets\AssetThumbnail.cs:line 176
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Editor.AssetThumbnail.RenderAssetThumb(Asset asset)
   at Editor.AssetThumbnail.RenderThumbnailAsync(Asset asset) in C:\build\_work\sbox\sbox\engine\Sandbox.Tools\Assets\AssetThumbnail.cs:line 131
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at Sandbox.Tasks.ExpirableSynchronizationContext.ProcessQueue() in C:\build\_work\sbox\sbox\engine\Sandbox.Engine\Threads\ExpirableSynchronizationContext.cs:line 421
   at Sandbox.EngineLoop.RunAsyncTasks() in C:\build\_work\sbox\sbox\engine\Sandbox.Engine\EngineLoop.cs:line 221
   at Sandbox.EngineLoop.FrameEnd() in C:\build\_work\sbox\sbox\engine\Sandbox.Engine\EngineLoop.cs:line 232
   at Sandbox.EngineLoop.RunFrame(CMaterialSystem2AppSystemDict appDict, Boolean& wantsQuit) in C:\build\_work\sbox\sbox\engine\Sandbox.Engine\EngineLoop.cs:line 53
   at Sandbox.AppSystem.RunFrame() in C:\build\_work\sbox\sbox\engine\Sandbox.AppSystem\AppSystem.cs:line 86
   at Sandbox.AppSystem.Run() in C:\build\_work\sbox\sbox\engine\Sandbox.AppSystem\AppSystem.cs:line 65
   at Sandbox.Launcher.Main() in C:\build\_work\sbox\sbox\engine\Launcher\SboxDev\Launcher.cs:line 24
   at Sandbox.Program.Launch() in C:\build\_work\sbox\sbox\engine\Launcher\Shared\Startup.cs:line 21
   at Sandbox.Program.Main() in C:\build\_work\sbox\sbox\engine\Launcher\Shared\Startup.cs:line 16
   
   https://github.com/user-attachments/assets/2ebad046-e9e4-4285-b7bf-6d5b2eb907dd

### Additional context

This happens when opening my prefab particles folder. DM me or Yart for the project if it will help

**Comment by Nolankicks** [comment]
I think Layla fixed this
