### ISSUE TITLE
`SvgPanel` ReloadTexture() throw error

### ISSUE THREAD

**Issue by PolSpock** [Facepunch/sbox-issues#6360]
### Describe the bug

Hi,

Since the resolution of the issue https://github.com/Facepunch/sbox-issues/issues/6247 (I assume), an error is being thrown when refreshing SVGs:

```
Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Sandbox.UI.SvgPanel.ReloadTexture() in C:\build\_work\sbox\sbox\engine\Sandbox.Game\UI2\Controls\SvgPanel.cs:line 74
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Sandbox.Tasks.ExpirableSynchronizationContext.ProcessQueue() in C:\build\_work\sbox\sbox\engine\Sandbox.Engine\Threads\ExpirableSynchronizationContext.cs:line 421
```

### To Reproduce

1) Download https://github.com/Facepunch/sbox-scenestaging
2) Edit `NameTagPanel.razor` with :
```
@using Sandbox;
@using Sandbox.UI;
@inherits PanelComponent

<root>

	<div class="card">
		<div class="name">@Name</div>
		@if (TargetObject is not null)
		{
			<div class="gameobject">@TargetObject.Name</div>
		}
		@if (true)
		{
			Log.Info("Rebuilding ! " + GetPath());
			<svg src="@GetPath()" ></svg>
		}
	</div>

</root>

@code {

	[Property] public string Name { get; set; } = "Mingebag";

	/// <summary>
	/// Testing something a bit dynamic to make sure serialized properly
	/// </summary>
	[Property] public GameObject TargetObject { get; set; }

	[Property] public bool SwitchSVG { get; set; }

	protected override void OnUpdate()
	{
		base.OnUpdate();

		if (Input.Pressed("Attack1"))
		{
			SwitchSVG = !SwitchSVG;
		}
	}

	public string GetPath()
	{
		return SwitchSVG ? "test1.svg" : "test2.svg";
	}

	/// <summary>
	/// the hash determines if the system should be rebuilt. If it changes, it will be rebuilt
	/// </summary>
	protected override int BuildHash()
	{
		Log.Info("SwitchSVG : " + SwitchSVG);
		return System.HashCode.Combine(Name, TargetObject, SwitchSVG);
	}
}
```
3) Edit `NameTagPanel.razor.scss` and add the following:
```
svg {
    width: 32px;
    height: 32px;
}
```
4) Start `networking.scene` and check console, you will get the error :
```
Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Sandbox.UI.SvgPanel.ReloadTexture() in C:\build\_work\sbox\sbox\engine\Sandbox.Game\UI2\Controls\SvgPanel.cs:line 74
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Sandbox.Tasks.ExpirableSynchronizationContext.ProcessQueue() in C:\build\_work\sbox\sbox\engine\Sandbox.Engine\Threads\ExpirableSynchronizationContext.cs:line 421
```

### Expected behavior

No error

### Media/Files

![image](https://github.com/user-attachments/assets/0cbee3a7-0c9d-4de6-ba9c-59882a102aeb)

**Comment by solwllms** [comment]
Cheers for flagging this, should be sorted now

**Comment by PolSpock** [comment]
All good 💌
