### ISSUE TITLE
UpdateFromPrefab gives object reference error if the prefab has prefab variables

### ISSUE THREAD

**Issue by SwagAccount** [Facepunch/sbox-issues#6363]
### Describe the bug

"Object reference not set to an instance of an object." when running panel event "onclick" from "Sandbox.UI.Panel"
System.NullReferenceException: Object reference not set to an instance of an object.
   at Sandbox.GameObject.SerializePrefabVariables() in C:\build\_work\sbox\sbox\engine\Sandbox.Game\Scene\GameObject\GameObject.Prefab.cs:line 201
   at Sandbox.GameObject.Serialize(SerializeOptions options) in C:\build\_work\sbox\sbox\engine\Sandbox.Game\Scene\GameObject\GameObject.Serialize.cs:line 115
   at Sandbox.GameObject.UpdateFromPrefab() in C:\build\_work\sbox\sbox\engine\Sandbox.Game\Scene\GameObject\GameObject.Prefab.cs:line 55
   at DMD<System.Void SpellMaker:CreateSpell(System.String)>(SpellMaker this, String file)
   at DMD<System.Void SpellUI+<>c__DisplayClass1_2:<BuildRenderTree>b__4()>(<>c__DisplayClass1_2 this)
   at Sandbox.UI.Panel.OnEvent(PanelEvent e)
   at Sandbox.UI.Panel.RunPendingEvents()
   
`GameObject spawned = new GameObject();
spawned.SetPrefabSource($"{PrefabDir}/{file}");
spawned.UpdateFromPrefab();`

### To Reproduce

[https://github.com/SwagAccount/s_box_issue_testing](https://github.com/SwagAccount/s_box_issue_testing)
1. Copy Path of Cube into PrefabSpawner's File Property
2. Press Spawn - no error
1. Copy Path of Cube with variables into PrefabSpawner's File Property
2. Press Spawn - error

### Expected behavior

not giving object ref error.

**Comment by aylaylay** [comment]
Fixed
