### ISSUE TITLE
Value cannot be null error 

### ISSUE THREAD

**Issue by EternalDawn1** [Facepunch/sbox-issues#6437]
### Describe the bug

Value cannot be null. (Parameter 'key')
System.ArgumentNullException: Value cannot be null. (Parameter 'key')
   at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at Sandbox.Services.Stats.PlayerStats.TryGet(String name, PlayerStat& stat) in C:\build\_work\sbox\sbox\engine\Sandbox.Engine\Services\Stats\Stats.Player.cs:line 98
   at Sandbox.Services.Stats.PlayerStats.Get(String name) in C:\build\_work\sbox\sbox\engine\Sandbox.Engine\Services\Stats\Stats.Player.cs:line 87
   at Sandbox.AchievementCollection.UnlockTest(Achievement entry, PlayerStats stats) in C:\build\_work\sbox\sbox\engine\Sandbox.Engine\Assets\AchievementCollection.cs:line 124
   at Sandbox.AchievementCollection.TestAchivementsForUnlock() in C:\build\_work\sbox\sbox\engine\Sandbox.Engine\Assets\AchievementCollection.cs:line 109
   at Sandbox.Services.Achievements.Tick() in C:\build\_work\sbox\sbox\engine\Sandbox.Engine\Services\Achievements\Achievements.cs:line 35
   at Sandbox.GameInstanceDll.Tick() in C:\build\_work\sbox\sbox\engine\Sandbox.GameInstance\GameInstanceDll.cs:line 258
   at Sandbox.EngineLoop.FrameStart() in C:\build\_work\sbox\sbox\engine\Sandbox.Engine\EngineLoop.cs:line 162
   at Sandbox.EngineLoop.RunFrame(CMaterialSystem2AppSystemDict appDict, Boolean& wantsQuit) in C:\build\_work\sbox\sbox\engine\Sandbox.Engine\EngineLoop.cs:line 36

### To Reproduce

i dont know , 

### Expected behavior

not an error

**Comment by aylaylay** [comment]
Fixed
