### ISSUE TITLE
Value cannot be null (Parameter source) 

### ISSUE THREAD

**Issue by EternalDawn1** [Facepunch/sbox-issues#6462]
### Describe the bug

when rightclicking , on the Hierarchy , to normally open up the menu to create a component , the error appears 

### To Reproduce

Value cannot be null. (Parameter 'source')
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source, Func`2 predicate)
   at Editor.GameObjectNode.<>c.<CreateObjectMenu>b__21_3(PrefabFile x) in R:\SteamLibrary\steamapps\common\sbox\addons\tools\Code\Scene\SceneTree\GameObjectNode.cs:line 477
   at System.Linq.EnumerableSorter`2.ComputeKeys(TElement[] elements, Int32 count)
   at System.Linq.EnumerableSorter`1.ComputeMap(TElement[] elements, Int32 count)
   at System.Linq.OrderedEnumerable`1.ToArray()
   at Editor.GameObjectNode.CreateObjectMenu(Menu menu, GameObject parent, Action`1 afterCreate) in R:\SteamLibrary\steamapps\common\sbox\addons\tools\Code\Scene\SceneTree\GameObjectNode.cs:line 474
   at Editor.GameObjectNode.AddGameObjectMenuItems(Menu m, TreeNode treeNode) in R:\SteamLibrary\steamapps\common\sbox\addons\tools\Code\Scene\SceneTree\GameObjectNode.cs:line 413
   at Editor.SceneNode.OnContextMenu() in R:\SteamLibrary\steamapps\common\sbox\addons\tools\Code\Scene\SceneTree\SceneNode.cs:line 66
   at Editor.SceneTreeWidget.OpenTreeViewContextMenu() in R:\SteamLibrary\steamapps\common\sbox\addons\tools\Code\Scene\SceneTree\SceneTree.cs:line 118
   at Editor.BaseItemWidget.OnMousePress(MouseEvent e) in C:\build\_work\sbox\sbox\engine\Sandbox.Tools\Widgets\BaseItemWidget.cs:line 369
   at Editor.TreeView.OnMousePress(MouseEvent e) in R:\SteamLibrary\steamapps\common\sbox\addons\tools\Code\Widgets\TreeView\TreeView.cs:line 680
   at Editor.Widget.InternalMousePressEvent(QMouseEvent e) in C:\build\_work\sbox\sbox\engine\Sandbox.Tools\Qt\Widget.Events.cs:line 138
   at Managed.SourceTools.Exports.Editor_BaseScrollWidget_InternalMousePressEvent(UInt32 self, IntPtr e) in C:\build\_work\sbox\sbox\engine\Sandbox.Tools\Interop.Tools.cs:line 15630

### Expected behavior

not the error 

### Media/Files

https://github.com/user-attachments/assets/49eb09c3-492f-4a7f-a80e-29be6f80c593

**Comment by aylaylay** [comment]
Should be fixed now
