### ISSUE TITLE
Unit tests for scenes

### ISSUE THREAD

**Issue by MrBrax** [Facepunch/sbox-issues#6486]
### For?

S&Box

### What can't you do?

Can't do testing for components and systems in the scene, only for standalone code. Would be great to be able to test ingame logic.

### How would you like it to work?

Like unit tests work currently but for scene stuff, maybe scene.push-like?

### What have you tried?

Loading scenes did not work, it always returned weird stuff.

**Comment by garrynewman** [comment]
This should work already

**Comment by MrBrax** [comment]
What's the path for loading scenes? I've tried things like this:
```
var opt = new SceneLoadOptions() { };
opt.SetScene( ResourceLibrary.Get<SceneFile>( "scenes/testing.scene" ) );

or

opt.SetScene( "C:/Users/Braxen/Documents/s&box projects/farm_merge/Assets/scenes/testing.scene" );

scene.Load( opt );
```

But the scene directory is always empty, tried pushing scene too but it did nothing

**Comment by DoctorGurke** [comment]
Can confirm loading scenes does not work in unit tests.
```
Standard Output: 
  08:45:02 Generic  LoadFromFile: Couldn't find Scenes/minimal.scene
  08:45:02 Generic  No valid Scene was found in SceneLoadOptions.
```
```csharp
var scene = new Scene();
var slo = new SceneLoadOptions();
slo.SetScene( $"Scenes/minimal.scene" );
scene.Load( slo );
```

**Comment by suiramdev** [comment]
Indeed. I tried to call `EditorScene.NewScene();` but this results in 

```
[Failed] GetGameObjectByNameTest
    Message:
        Test method GameObjectToolTest.GetGameObjectByNameTest threw exception: 
        System.NullReferenceException: Object reference not set to an instance of an object.
    Stack Trace:
            at Editor.SceneEditorSession.CreateSceneDock()
           at Editor.SceneEditorSession..ctor(Scene scene)
           at Editor.EditorScene.NewScene()
           at GameObjectToolTest.GetGameObjectByNameTest()
           at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
           at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
    Standard Output Messages:
        07:25:15 engine/R Error loading resource file "models/dev/error.vmesh_c" (Error: ERROR_FILEOPEN: File not found)
```
