### ISSUE TITLE
RPC Error appear 

### ISSUE THREAD

**Issue by EternalDawn1** [Facepunch/sbox-issues#6500]
### Describe the bug

OnObjectMessage: Unknown GameObject b9354994-a078-492e-9e94-da09eec15f50 for RPC UpdateInteractions
   at Sandbox.Rpc.HandleIncoming(ObjectMessageMsg message, Connection source) in C:\build\_work\sbox\sbox\engine\Sandbox.Game\Scene\Networking\Rpc.cs:line 327
   at Sandbox.SceneNetworkSystem.OnObjectMessage(ObjectMessageMsg message, Connection source, Guid msgid) in C:\build\_work\sbox\sbox\engine\Sandbox.Game\Scene\Networking\SceneNetworkSystem.cs:line 392
   at Sandbox.Network.NetworkSystem.<>c__DisplayClass82_0`1.<AddHandler>b__0(Object o, Connection channel, Guid g) in C:\build\_work\sbox\sbox\engine\Sandbox.Engine\Networking\System\NetworkSystem.Message.cs:line 36
   at Sandbox.Network.NetworkSystem.HandleIncomingMessage(NetworkMessage msg) in C:\build\_work\sbox\sbox\engine\Sandbox.Engine\Networking\System\NetworkSystem.Message.cs:line 208
   at Sandbox.Network.TcpChannel.InternalRecv(MessageHandler handler) in C:\build\_work\sbox\sbox\engine\Sandbox.Engine\Networking\Transports\Tcp\TcpChannel.cs:line 181
   at Sandbox.Connection.GetIncomingMessages(MessageHandler handler) in C:\build\_work\sbox\sbox\engine\Sandbox.Engine\Networking\System\Channel\Connection.cs:line 173
   at Sandbox.Network.TcpSocket.GetIncomingMessages(MessageHandler handler) in C:\build\_work\sbox\sbox\engine\Sandbox.Engine\Networking\Transports\Tcp\TcpSocket.cs:line 94
   at Sandbox.Network.NetworkSystem.ProcessIncomingMessages() in C:\build\_work\sbox\sbox\engine\Sandbox.Engine\Networking\System\NetworkSystem.Message.cs:line 80
   at Sandbox.Network.NetworkSystem.Tick() in C:\build\_work\sbox\sbox\engine\Sandbox.Engine\Networking\System\NetworkSystem.cs:line 96
   at Sandbox.Networking.Tick() in C:\build\_work\sbox\sbox\engine\Sandbox.Engine\Networking\Networking.cs:line 62
   at Sandbox.GameInstanceDll.Tick() in C:\build\_work\sbox\sbox\engine\Sandbox.GameInstance\GameInstanceDll.cs:line 239
   at Sandbox.EngineLoop.FrameStart() in C:\build\_work\sbox\sbox\engine\Sandbox.Engine\EngineLoop.cs:line 162
   at Sandbox.EngineLoop.RunFrame(CMaterialSystem2AppSystemDict appDict, Boolean& wantsQuit) in C:\build\_work\sbox\sbox\engine\Sandbox.Engine\EngineLoop.cs:line 36
   at Sandbox.AppSystem.RunFrame() in C:\build\_work\sbox\sbox\engine\Sandbox.AppSystem\AppSystem.cs:line 105
   at Sandbox.AppSystem.Run() in C:\build\_work\sbox\sbox\engine\Sandbox.AppSystem\AppSystem.cs:line 84
   at Sandbox.Launcher.Main() in C:\build\_work\sbox\sbox\engine\Launcher\SboxDev\Launcher.cs:line 24
   at Sandbox.Program.Launch() in C:\build\_work\sbox\sbox\engine\Launcher\Shared\Startup.cs:line 21
   at Sandbox.Program.Main() in C:\build\_work\sbox\sbox\engine\Launcher\Shared\Startup.cs:line 16

### To Reproduce

using an RPC [Broadcast]

### Expected behavior

.

**Comment by EternalDawn1** [comment]
solved by setting the object to networked mode, instead of snapshot
