### ISSUE TITLE
Whitelist System.Numerics

### ISSUE THREAD

**Issue by kEllieGit** [Facepunch/sbox-issues#6546]
### What it is?

Two whitelist errors trying to add two INumbers

Whitelist Error: RPG.Stat`1.Add(..) - [CallAbstract]	Call not allowed on abstract methods.
   at Sandbox.PackageLoader.TestAccessControl(Stream dll, TrustedBinaryStream& trustedDll) in C:\build\_work\sbox\sbox\engine\Sandbox.Engine\Assets\PackageManager\PackageLoader.cs:line 97
   at Sandbox.PackageLoader.LoadAssemblyFromPackage(ActivePackage ap, String filename, Byte[] bytes) in C:\build\_work\sbox\sbox\engine\Sandbox.Engine\Assets\PackageManager\PackageLoader.cs:line 247
   at Sandbox.PackageLoader.LoadPendingChanges() in C:\build\_work\sbox\sbox\engine\Sandbox.Engine\Assets\PackageManager\PackageLoader.cs:line 138
   at Sandbox.PackageLoader.Tick() in C:\build\_work\sbox\sbox\engine\Sandbox.Engine\Assets\PackageManager\PackageLoader.cs:line 695
   at Sandbox.GameInstanceDll.FinishLoadingAssemblies() in C:\build\_work\sbox\sbox\engine\Sandbox.GameInstance\GameInstanceDll.cs:line 222
   at Sandbox.GameInstanceDll.Tick() in C:\build\_work\sbox\sbox\engine\Sandbox.GameInstance\GameInstanceDll.cs:line 245
   at Sandbox.EngineLoop.FrameStart() in C:\build\_work\sbox\sbox\engine\Sandbox.Engine\EngineLoop.cs:line 162
   at Sandbox.EngineLoop.RunFrame(CMaterialSystem2AppSystemDict appDict, Boolean& wantsQuit) in C:\build\_work\sbox\sbox\engine\Sandbox.Engine\EngineLoop.cs:line 36
   at Sandbox.AppSystem.RunFrame() in C:\build\_work\sbox\sbox\engine\Sandbox.AppSystem\AppSystem.cs:line 106
   at Sandbox.AppSystem.Run() in C:\build\_work\sbox\sbox\engine\Sandbox.AppSystem\AppSystem.cs:line 85
   at Sandbox.Launcher.Main() in C:\build\_work\sbox\sbox\engine\Launcher\SboxDev\Launcher.cs:line 24
   at Sandbox.Program.Launch() in C:\build\_work\sbox\sbox\engine\Launcher\Shared\Startup.cs:line 21
   at Sandbox.Program.Main() in C:\build\_work\sbox\sbox\engine\Launcher\Shared\Startup.cs:line 16

Whitelist Error: RPG.Stat`1.Add(..) - [Constrained]	Missing callvirt following constrained prefix.
   at Sandbox.PackageLoader.TestAccessControl(Stream dll, TrustedBinaryStream& trustedDll) in C:\build\_work\sbox\sbox\engine\Sandbox.Engine\Assets\PackageManager\PackageLoader.cs:line 97
   at Sandbox.PackageLoader.LoadAssemblyFromPackage(ActivePackage ap, String filename, Byte[] bytes) in C:\build\_work\sbox\sbox\engine\Sandbox.Engine\Assets\PackageManager\PackageLoader.cs:line 247
   at Sandbox.PackageLoader.LoadPendingChanges() in C:\build\_work\sbox\sbox\engine\Sandbox.Engine\Assets\PackageManager\PackageLoader.cs:line 138
   at Sandbox.PackageLoader.Tick() in C:\build\_work\sbox\sbox\engine\Sandbox.Engine\Assets\PackageManager\PackageLoader.cs:line 695
   at Sandbox.GameInstanceDll.FinishLoadingAssemblies() in C:\build\_work\sbox\sbox\engine\Sandbox.GameInstance\GameInstanceDll.cs:line 222
   at Sandbox.GameInstanceDll.Tick() in C:\build\_work\sbox\sbox\engine\Sandbox.GameInstance\GameInstanceDll.cs:line 245
   at Sandbox.EngineLoop.FrameStart() in C:\build\_work\sbox\sbox\engine\Sandbox.Engine\EngineLoop.cs:line 162
   at Sandbox.EngineLoop.RunFrame(CMaterialSystem2AppSystemDict appDict, Boolean& wantsQuit) in C:\build\_work\sbox\sbox\engine\Sandbox.Engine\EngineLoop.cs:line 36
   at Sandbox.AppSystem.RunFrame() in C:\build\_work\sbox\sbox\engine\Sandbox.AppSystem\AppSystem.cs:line 106
   at Sandbox.AppSystem.Run() in C:\build\_work\sbox\sbox\engine\Sandbox.AppSystem\AppSystem.cs:line 85
   at Sandbox.Launcher.Main() in C:\build\_work\sbox\sbox\engine\Launcher\SboxDev\Launcher.cs:line 24
   at Sandbox.Program.Launch() in C:\build\_work\sbox\sbox\engine\Launcher\Shared\Startup.cs:line 21
   at Sandbox.Program.Main() in C:\build\_work\sbox\sbox\engine\Launcher\Shared\Startup.cs:line 16

### Why do you need to use this?

Since dynamic isn't allowed (and I probably think it shouldn't), there is no simple way to add 2 different number types together without creating a casting hell.

INumber would fix this issue, but adding 2 INumbers together is not allowed, see the above whitelist errors.

My code:

```
using System;
using System.Numerics;

namespace RPG;

public class Stat<T> where T : INumber<T>
{
	public T BaseValue { get; set; }
	public T Modifier { get; set; }

	public Stat( T baseValue )
	{
		BaseValue = baseValue;
		Modifier = default;
	}

	/// <summary>
	/// Returns the final value after applying the modifier to the base value.
	/// </summary>
	public T GetFinalValue()
	{
		return Add( BaseValue, Modifier );
	}

	public static implicit operator T( Stat<T> stat )
	{
		return stat.GetFinalValue();
	}

	public static implicit operator Stat<T>( T value )
	{
		return new Stat<T>( value );
	}

	/// <summary>
	/// Adds two values of type T. Only works for numeric types.
	/// </summary>
	private static T Add( T a, T b )
	{
		return a + b;
	}
}
```

**Comment by handsomematt** [comment]
Will be resolved with #6557
