### ISSUE TITLE
VPK not loading in uploaded map scene

### ISSUE THREAD

**Issue by KingOfTheFBI** [Facepunch/sbox-issues#6620]
### Describe the bug

When I go to play a map with a custom scene I uploaded on the main s&box game the VPK fails to load.
![Image](https://github.com/user-attachments/assets/e096ec4a-09e7-4791-b7ff-ea28f98f463f)

It throws these two errors:

[engine/WorldRenderer] Failed to mount vpk for maps/scenes/aesthetic_mall_final. Has the map been compiled?
   at Sandbox.EngineLoop.Print(Int32 severity, String logger, String message) in C:\build\_work\sbox\sbox\engine\Sandbox.Engine\EngineLoop.cs:line 340
   at Managed.SandboxEngine.Exports.Sandbox_EngineLoop_Print(Int32 severitty, IntPtr logger, IntPtr message) in C:\build\_work\sbox\sbox\engine\Sandbox.Engine\Interop.Engine.cs:line 11764
   at Sandbox.SceneMap.CreateWorld(SceneWorld sceneWorld, String map, Boolean async, Vector3 origin) in C:\build\_work\sbox\sbox\engine\Sandbox.Engine\SceneSystem\SceneMap.cs:line 111
   at Sandbox.SceneMap..ctor(SceneWorld sceneWorld, String map, MapLoader loader) in C:\build\_work\sbox\sbox\engine\Sandbox.Engine\SceneSystem\SceneMap.cs:line 75
   at Sandbox.MapInstance.LoadMapAsync(String mapName) in C:\build\_work\sbox\sbox\engine\Sandbox.Game\Scene\Components\Map\MapInstance.cs:line 286
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Sandbox.MapInstance.LoadMapAsync(String mapName)
   at Sandbox.MapInstance.OnLoad() in C:\build\_work\sbox\sbox\engine\Sandbox.Game\Scene\Components\Map\MapInstance.cs:line 126
   at Sandbox.Component.LaunchLoader() in C:\build\_work\sbox\sbox\engine\Sandbox.Game\Scene\Components\Component.Loading.cs:line 13
   at Sandbox.CallbackBatch.Group.Execute(CallbackBatch parent) in C:\build\_work\sbox\sbox\engine\Sandbox.Game\Scene\GameObject\CallbackBatch.cs:line 45
   at Sandbox.CallbackBatch.Execute() in C:\build\_work\sbox\sbox\engine\Sandbox.Game\Scene\GameObject\CallbackBatch.cs:line 127
   at Sandbox.CallbackBatch.Dispose() in C:\build\_work\sbox\sbox\engine\Sandbox.Game\Scene\GameObject\CallbackBatch.cs:line 139
   at Sandbox.Scene.Load(SceneLoadOptions options)
   at Sandbox.GameInstance.OpenStartupScene() in C:\build\_work\sbox\sbox\engine\Sandbox.GameInstance\GameInstance.cs:line 485
   at Sandbox.GameInstanceDll.LoadGamePackageAsync(String ident, GameLoadingFlags flags, CancellationToken ct) in C:\build\_work\sbox\sbox\engine\Sandbox.GameInstance\GameInstanceDll.cs:line 438
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
   at Sandbox.Tasks.ExpirableSynchronizationContext.ProcessQueue() in C:\build\_work\sbox\sbox\engine\Sandbox.Engine\Threads\ExpirableSynchronizationContext.cs:line 421
   at Sandbox.EngineLoop.RunAsyncTasks() in C:\build\_work\sbox\sbox\engine\Sandbox.Engine\EngineLoop.cs:line 221
   at Sandbox.EngineLoop.FrameStart() in C:\build\_work\sbox\sbox\engine\Sandbox.Engine\EngineLoop.cs:line 130
   at Sandbox.EngineLoop.RunFrame(CMaterialSystem2AppSystemDict appDict, Boolean& wantsQuit) in C:\build\_work\sbox\sbox\engine\Sandbox.Engine\EngineLoop.cs:line 36
   at Sandbox.AppSystem.RunFrame() in C:\build\_work\sbox\sbox\engine\Sandbox.AppSystem\AppSystem.cs:line 106
   at Sandbox.AppSystem.Run() in C:\build\_work\sbox\sbox\engine\Sandbox.AppSystem\AppSystem.cs:line 85
   at Sandbox.Launcher.Main() in C:\build\_work\sbox\sbox\engine\Launcher\Sbox\Launcher.cs:line 8
   at Sandbox.Program.Launch() in C:\build\_work\sbox\sbox\engine\Launcher\Shared\Startup.cs:line 21
   at Sandbox.Program.Main() in C:\build\_work\sbox\sbox\engine\Launcher\Shared\Startup.cs:line 16

[GameMenu] Couldn't load map (Unable to create world for map 'scenes/aesthetic_mall_final')
System.Exception: Unable to create world for map 'scenes/aesthetic_mall_final'
   at Sandbox.SceneMap.CreateWorld(SceneWorld sceneWorld, String map, Boolean async, Vector3 origin) in C:\build\_work\sbox\sbox\engine\Sandbox.Engine\SceneSystem\SceneMap.cs:line 123
   at Sandbox.SceneMap..ctor(SceneWorld sceneWorld, String map, MapLoader loader) in C:\build\_work\sbox\sbox\engine\Sandbox.Engine\SceneSystem\SceneMap.cs:line 75
   at Sandbox.MapInstance.LoadMapAsync(String mapName) in C:\build\_work\sbox\sbox\engine\Sandbox.Game\Scene\Components\Map\MapInstance.cs:line 286

The map is compiled and even has the same name as the scene. It shows up properly on the editor. 
On upload it is also uploading the VPK with the scene so it should be working. 
The project type is an addon. 
I tried multiple other maps and the scene does the same thing
Other objects in the scene load

### To Reproduce

Here is a scene that does the error:
[aesthetic_mall_test.zip](https://github.com/user-attachments/files/17389150/aesthetic_mall_test.zip)

You can play it on s&box here and see the error
https://sbox.game/fyn/aesthetic_mall_test

### Expected behavior

Should be loading the VPK

**Comment by KingOfTheFBI** [comment]
@solwllms looks to be fixed, thank you!
