### ISSUE TITLE
Deleting a component retrieved with TryGet results in engine IndexOutOfRange error

### ISSUE THREAD

**Issue by trundlr** [Facepunch/sbox-issues#6648]
### Describe the bug

In Micro Mayhem, I am refactoring some of the code, and received an error while destroying a component fetched within a TryGet:
```cs
if ( Components.TryGet( out WardrobeCamera tempCamera ) )
	tempCamera.Destroy();
```

The error:
```
Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at Sandbox.Utility.HashSetEx`1.EnumerateLocked(Boolean nullChecks)+MoveNext() in C:\build\_work\sbox\sbox\engine\Sandbox.System\Collections\HashSetEx.cs:line 124
   at Sandbox.Scene.Update() in C:\build\_work\sbox\sbox\engine\Sandbox.Game\Scene\Scene\Scene.Tick.cs:line 153
   at Sandbox.Scene.SharedTick() in C:\build\_work\sbox\sbox\engine\Sandbox.Game\Scene\Scene\Scene.Tick.cs:line 229
   at Sandbox.Scene.GameTick() in C:\build\_work\sbox\sbox\engine\Sandbox.Game\Scene\Scene\Scene.Tick.cs:line 278
   at Sandbox.Game.Frame() in C:\build\_work\sbox\sbox\engine\Sandbox.Game\Game\Game.Scene.cs:line 33
   at Sandbox.GameInstanceDll.Tick() in C:\build\_work\sbox\sbox\engine\Sandbox.GameInstance\GameInstanceDll.cs:line 278
   at Sandbox.EngineLoop.FrameStart() in C:\build\_work\sbox\sbox\engine\Sandbox.Engine\EngineLoop.cs:line 212
   at Sandbox.EngineLoop.RunFrame(CMaterialSystem2AppSystemDict appDict, Boolean& wantsQuit) in C:\build\_work\sbox\sbox\engine\Sandbox.Engine\EngineLoop.cs:line 64
```

### To Reproduce

1. Use TryGet and Destroy the component
2. Observe error

### Expected behavior

No error

**Comment by matekdev** [comment]
We were getting the same error with the following code
```csharp
if ( _modelPhysics.IsValid() )
	_modelPhysics.Destroy();
```
![Image](https://github.com/user-attachments/assets/bd363af5-b791-4f4b-88bf-5aec150494c6)

If you need a repro contact me on discord.

**Comment by matekdev** [comment]
I believe this is fixed and can be closed @trundlr 
https://discord.com/channels/833983068468936704/835035328779518023/1297789672990445630

thanks garry
