### ISSUE TITLE
LobbyCard NRE

### ISSUE THREAD

**Issue by Nolankicks** [Facepunch/sbox-issues#6833]
### Describe the bug

The lobby card panel has an NRE.

### To Reproduce

1. Open the menu

### Expected behavior

Should not have an NRE

### Media/Files

Error when building render tree on LobbyCard - Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at LobbyCard.<>c.<BuildRenderTree>b__1_1(LobbyInformation l) in MenuUI/Front/LobbyCard.razor:line 16
   at System.Linq.Enumerable.WhereListIterator`1.GetCount(Boolean onlyIfCheap)
   at LobbyCard.BuildRenderTree(RenderTreeBuilder __builder) in MenuUI/Front/LobbyCard.razor:line 17
   at Sandbox.UI.Panel.InternalRenderTree() in C:\build\_work\sbox\sbox\engine\Sandbox.Game\UI2\Panel\Panel.Razor.cs:line 106

### Additional context

Only started happening after dedi server branch was merged today

**Comment by aylaylay** [comment]
Should be fixed now
