### ISSUE TITLE
[Graphics] Graphics.RenderToTexture() can't render a texture without MSAA

### ISSUE THREAD

**Issue by ryantrawick** [Facepunch/sbox-issues#6879]
### Describe the bug

When using Graphics.RenderToTexture() to render a SceneCamera with antiAliasing set to false, and a RenderTarget (Texture) with MSAA set to MultisampleAmount.MultisampleNone, it spits out an error about the Overlay part of the pipeline expecting a texture with MSAA:

```
Error: View "RenderScene", layer "UI Overlay", render target "overlay_depth....": 
	Attempted to set up a render target output w/ MSAA 0 where the color targets have different MSAA settings 4!
   at Sandbox.EngineLoop.Print(Int32 severity, String logger, String message) in C:\build\_work\sbox\sbox\engine\Sandbox.Engine\EngineLoop.cs:line 340
   at Managed.SandboxEngine.Exports.Sandbox_EngineLoop_Print(Int32 severitty, IntPtr logger, IntPtr message) in C:\build\_work\sbox\sbox\engine\Sandbox.Engine\Interop.Engine.cs:line 12136
   at Sandbox.Graphics.RenderToTexture(SceneCamera camera, Texture target) in C:\build\_work\sbox\sbox\engine\Sandbox.Engine\Render\Graphics.cs:line 285
   at LineCamera.OnUpdate() in C:\users\ryan\documents\s&box projects\egogia\Code\LineCamera.cs:line 44
   at Sandbox.Component.InternalUpdate() in C:\build\_work\sbox\sbox\engine\Sandbox.Game\Scene\Components\Component.Update.cs:line 51
   at Sandbox.Scene.Update() in C:\build\_work\sbox\sbox\engine\Sandbox.Game\Scene\Scene\Scene.Tick.cs:line 158
   at Sandbox.Scene.SharedTick() in C:\build\_work\sbox\sbox\engine\Sandbox.Game\Scene\Scene\Scene.Tick.cs:line 212
   at Sandbox.Scene.GameTick() in C:\build\_work\sbox\sbox\engine\Sandbox.Game\Scene\Scene\Scene.Tick.cs:line 283
   at Sandbox.Game.Frame() in C:\build\_work\sbox\sbox\engine\Sandbox.Game\Game\Game.Scene.cs:line 30
   at Sandbox.GameInstanceDll.Tick() in C:\build\_work\sbox\sbox\engine\Sandbox.GameInstance\GameInstanceDll.cs:line 252
   at Sandbox.EngineLoop.FrameStart() in C:\build\_work\sbox\sbox\engine\Sandbox.Engine\EngineLoop.cs:line 163
   at Sandbox.EngineLoop.RunFrame(CMaterialSystem2AppSystemDict appDict, Boolean& wantsQuit) in C:\build\_work\sbox\sbox\engine\Sandbox.Engine\EngineLoop.cs:line 36
   at Sandbox.AppSystem.RunFrame() in C:\build\_work\sbox\sbox\engine\Sandbox.AppSystem\AppSystem.cs:line 106
   at Sandbox.AppSystem.Run() in C:\build\_work\sbox\sbox\engine\Sandbox.AppSystem\AppSystem.cs:line 85
   at Sandbox.Launcher.Main() in C:\build\_work\sbox\sbox\engine\Launcher\SboxDev\Launcher.cs:line 24
   at Sandbox.Program.Launch() in C:\build\_work\sbox\sbox\engine\Launcher\Shared\Startup.cs:line 21
   at Sandbox.Program.Main() in C:\build\_work\sbox\sbox\engine\Launcher\Shared\Startup.cs:line 16

Error: View "RenderScene", layer "OverlayWithDepth", render target "intermediate_depth_stereo_rt....": 
	Attempted to set up a render target output w/ MSAA 0 where the color targets have different MSAA settings 4!
   at Sandbox.EngineLoop.Print(Int32 severity, String logger, String message) in C:\build\_work\sbox\sbox\engine\Sandbox.Engine\EngineLoop.cs:line 340
   at Managed.SandboxEngine.Exports.Sandbox_EngineLoop_Print(Int32 severitty, IntPtr logger, IntPtr message) in C:\build\_work\sbox\sbox\engine\Sandbox.Engine\Interop.Engine.cs:line 12136
   at Sandbox.Graphics.RenderToTexture(SceneCamera camera, Texture target) in C:\build\_work\sbox\sbox\engine\Sandbox.Engine\Render\Graphics.cs:line 285
   at DMD<System.Void LineCamera:OnUpdate()>(LineCamera this)
   at Sandbox.Component.InternalUpdate()
   at Sandbox.Scene.Update()
   at Sandbox.Scene.SharedTick()
   at Sandbox.Scene.GameTick()
   at Sandbox.Game.Frame()
   at Sandbox.GameInstanceDll.Tick()
   at Sandbox.EngineLoop.FrameStart()
   at Sandbox.EngineLoop.RunFrame(CMaterialSystem2AppSystemDict appDict, Boolean& wantsQuit)
   at Sandbox.AppSystem.RunFrame()
   at Sandbox.AppSystem.Run()
   at Sandbox.Launcher.Main()
   at Sandbox.Program.Launch()
   at Sandbox.Program.Main()
```

If you set antiAliasing to true on the SceneCamera it doesn't have any errors, but the output framebuffer does still have MSAA resolved (along with some blue-noise dithering that makes the framebuffer useless further down the rendering pipeline).

### To Reproduce

Take this script and stick it on a GameObject with a Camera, and then run the game.

```c#
using Sandbox;

public sealed class LineCamera : Component
{
	public Texture RenderTarget { get; private set; }
	CameraComponent Camera { get; set; }
	SceneCamera SceneCamera { get; set; }

	public static LineCamera Instance { get; private set; }

	protected override void OnStart()
	{
		Instance = this;
		Camera = GetComponent<CameraComponent>();
		SceneCamera = new SceneCamera( "Line Camera" );
	}

	protected override void OnUpdate()
	{
		if ( RenderTarget == null || !RenderTarget.Size.AlmostEqual( Screen.Size, 0.5f ) )
		{
			RenderTarget?.Dispose();

			RenderTarget = Texture.CreateRenderTarget()
				.WithFormat( ImageFormat.RGBA8888 )
				.WithSize( Screen.Size )
				.WithMSAA( MultisampleAmount.MultisampleNone )
				.Create( "RawBuffer" );
		}

		Camera.UpdateSceneCamera( SceneCamera );
		SceneCamera.AntiAliasing = false;;

		Graphics.RenderToTexture( SceneCamera, RenderTarget );
	}

	protected override void OnDestroy()
	{
		RenderTarget?.Dispose();
		SceneCamera?.Dispose();
		Instance = null;
	}
}

### Expected behavior

No errors, and a framebuffer of the scene that doesn't have antialiasing (we also need to be able to disable the "Overlay"/blue noise dithering pass to make this function useful at all, see attached image for how noisy my edge-detection is due to the dithering).

![Image](https://github.com/user-attachments/assets/604d6973-48ba-45a9-9ff6-a9d7c5d8b94e)


### Media/Files

_No response_

### Additional context

_No response_

**Comment by aylaylay** [comment]
Should be fixed now - can you try it again please?

**Comment by ryantrawick** [comment]
It is indeed fixed.

You MUST set `SceneCamera.AntiAliasing = false;` before calling `Graphics.RenderToTexture( SceneCamera, RenderTarget );`, even if that RenderTarget Texture has `MultisampleAmount.MultisampleNone`.

So if I set it to `MultisampleAmount.Multisample8x`, it doesn't seem like there's a way for me to resolve it as far as I can tell.

Rendering without AA is possible now and that's what I needed, thank you.


The dither still persists however, I need very high-precision and accurate colors in the buffer, this is my shader with a low precision tolerance, you can see the boxes blend together:

![Image](https://github.com/user-attachments/assets/d38a195a-e3a6-4e34-b4dc-634681e4cfd4)

And here it is with the precision I need (I turned on tonemapping to see it better):

![Image](https://github.com/user-attachments/assets/52675f55-ac36-4427-9fcf-64de083955f6)

Seems there's a blue-noise-like dither that animates every frame, I found this slide from a Valve talk about their VR rendering, I'm guessing it's still hard-coded deep in the engine somewhere, along with the forced tonemapping:

![Image](https://github.com/user-attachments/assets/c57a8c61-ca3c-4724-8c87-f646266bfebc)

**Comment by aylaylay** [comment]
Is that a separate issue?
