### ISSUE TITLE
Using an action prefab variable makes the scene unable to run

### ISSUE THREAD

**Issue by ScoutWozniak** [Facepunch/sbox-issues#6880]
### Describe the bug

I've created a prefab that has an action as a prefab variable.  When I add it to my scene and set the action, the game breaks and I am unable to play the scene.  An error is in the console I will attach bellow.  This also creates weird behaviour when saving the prefab itself.

### To Reproduce

1. Create a prefab with an action
2. Set an action graph property as a prefab variable
3. Add it to a new scene and set the action
4. Run the scene
5. Have fun

### Expected behavior

I should be able to create an action on the prefab instance and the game should run!

### Media/Files

```
ActiveNodeLibrary not set when deserializing, we need to be inside a Scene.Push() or NodeLibrary.Push() context.
System.InvalidOperationException: ActiveNodeLibrary not set when deserializing, we need to be inside a Scene.Push() or NodeLibrary.Push() context.
   at Sandbox.Json.<>c.<Initialize>b__4_1() in C:\build\_work\sbox\sbox\engine\Sandbox.Engine\Utility\Json\Json.cs:line 48
   at Facepunch.ActionGraphs.ExtendedJsonConverter`1.Write(Utf8JsonWriter writer, T value, JsonSerializerOptions options) in /home/runner/work/ActionGraphs/ActionGraphs/Facepunch.ActionGraphs/Serialization.cs:line 188
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCoreAsObject(Utf8JsonWriter writer, Object value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteCoreAsObject(Utf8JsonWriter writer, Object value, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.WriteNodeAsObject(Object value, JsonTypeInfo jsonTypeInfo)
   at Sandbox.GameObject.SerializePrefabVariables() in C:\build\_work\sbox\sbox\engine\Sandbox.Game\Scene\GameObject\GameObject.Prefab.cs:line 240
   at Sandbox.GameObject.Serialize(SerializeOptions options) in C:\build\_work\sbox\sbox\engine\Sandbox.Game\Scene\GameObject\GameObject.Serialize.cs:line 240
   at Editor.SceneEditorSession.RefreshAllElements() in C:\build\_work\sbox\sbox\engine\Sandbox.Tools\Scene\Session\SceneEditorSession.Undo.cs:line 142
   at Editor.SceneEditorSession.CreateWholeSceneUndoSnapshot()
   at Sandbox.Helpers.UndoSystem.Initialize() in C:\build\_work\sbox\sbox\engine\Sandbox.Tools\Utility\UndoSystem.cs:line 181
   at Editor.SceneEditorSession.InitUndo() in C:\build\_work\sbox\sbox\engine\Sandbox.Tools\Scene\Session\SceneEditorSession.Undo.cs:line 18
   at Editor.SceneEditorSession..ctor(Scene scene) in C:\build\_work\sbox\sbox\engine\Sandbox.Tools\Scene\Session\SceneEditorSession.cs:line 58
   at Editor.GameEditorSession..ctor(SceneEditorSession parentSession, Scene scene) in C:\build\_work\sbox\sbox\engine\Sandbox.Tools\Scene\Session\GameEditorSession.cs:line 14
   at Editor.EditorScene.Play() in C:\build\_work\sbox\sbox\engine\Sandbox.Tools\Scene\EditorScene.cs:line 360
   at Editor.<PlayPause>F960C6D1802D6A9730B36DD73412CBFFC26C1F04C907A445CE95FBFCA6906F19E__PlayButton.OnMousePress(MouseEvent e) in C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\tools\Code\Editor\HeaderBar\PlayPause.cs:line 52
   at Editor.Widget.InternalMousePressEvent(QMouseEvent e) in C:\build\_work\sbox\sbox\engine\Sandbox.Tools\Qt\Widget.Events.cs:line 121
   at Managed.SourceTools.Exports.Editor_Widget_InternalMousePressEvent(UInt32 self, IntPtr e) in C:\build\_work\sbox\sbox\engine\Sandbox.Tools\Interop.Tools.cs:line 22575

```

**Comment by Metapyziks** [comment]
How action graphs work with prefab variables will need a rethink, it'll have to be after hackweek.
