### ISSUE TITLE
[Action Graph] Serialization error when using actions as a prefab variable

### ISSUE THREAD

**Issue by Fortune117** [Facepunch/sbox-issues#6891]
### Describe the bug

I have a prefab that looks like this:
![Image](https://github.com/user-attachments/assets/f128e750-662e-489e-9ed4-e5cf6e90003b)

The `test_child` prefab has an Action property that is set up to be a prefab variable:
![Image](https://github.com/user-attachments/assets/3e02eabf-5819-4e0b-b528-d44711eb4450)

If you add an action and try to save even an empty action, you get a serialization error:

```
Exception when serializing GameObject
System.InvalidOperationException: ActiveNodeLibrary not set when deserializing, we need to be inside a Scene.Push() or NodeLibrary.Push() context.
   at Sandbox.Json.<>c.<Initialize>b__4_1() in C:\build\_work\sbox\sbox\engine\Sandbox.Engine\Utility\Json\Json.cs:line 48
   at Facepunch.ActionGraphs.ExtendedJsonConverter`1.Write(Utf8JsonWriter writer, T value, JsonSerializerOptions options) in /home/runner/work/ActionGraphs/ActionGraphs/Facepunch.ActionGraphs/Serialization.cs:line 188
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCoreAsObject(Utf8JsonWriter writer, Object value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteCoreAsObject(Utf8JsonWriter writer, Object value, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.WriteNodeAsObject(Object value, JsonTypeInfo jsonTypeInfo)
   at Sandbox.GameObject.SerializePrefabVariables() in C:\build\_work\sbox\sbox\engine\Sandbox.Game\Scene\GameObject\GameObject.Prefab.cs:line 240
   at Sandbox.GameObject.Serialize(SerializeOptions options) in C:\build\_work\sbox\sbox\engine\Sandbox.Game\Scene\GameObject\GameObject.Serialize.cs:line 240
   at Sandbox.GameObject.Serialize(SerializeOptions options) in C:\build\_work\sbox\sbox\engine\Sandbox.Game\Scene\GameObject\GameObject.Serialize.cs:line 240
```

Additionally, I want to reference objects in the active prefab inside the prefab variable action:
![Image](https://github.com/user-attachments/assets/6b752bef-36f3-4565-8382-197b2d3e401f)

This throws an additional error, I don't know for sure if they're connected so I figured I'd mention both:
```
ActiveNodeLibrary not set when deserializing, we need to be inside a Scene.Push() or NodeLibrary.Push() context.
System.InvalidOperationException: ActiveNodeLibrary not set when deserializing, we need to be inside a Scene.Push() or NodeLibrary.Push() context.
   at Sandbox.Json.<>c.<Initialize>b__4_1() in C:\build\_work\sbox\sbox\engine\Sandbox.Engine\Utility\Json\Json.cs:line 48
   at Facepunch.ActionGraphs.ExtendedJsonConverter`1.Write(Utf8JsonWriter writer, T value, JsonSerializerOptions options) in /home/runner/work/ActionGraphs/ActionGraphs/Facepunch.ActionGraphs/Serialization.cs:line 188
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCoreAsObject(Utf8JsonWriter writer, Object value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteCoreAsObject(Utf8JsonWriter writer, Object value, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.WriteNodeAsObject(Object value, JsonTypeInfo jsonTypeInfo)
   at Sandbox.GameObject.SerializePrefabVariables() in C:\build\_work\sbox\sbox\engine\Sandbox.Game\Scene\GameObject\GameObject.Prefab.cs:line 240
   at Sandbox.GameObject.Serialize(SerializeOptions options) in C:\build\_work\sbox\sbox\engine\Sandbox.Game\Scene\GameObject\GameObject.Serialize.cs:line 240
   at Editor.SceneEditorSession.RefreshAllElements() in C:\build\_work\sbox\sbox\engine\Sandbox.Tools\Scene\Session\SceneEditorSession.Undo.cs:line 142
   at Editor.SceneEditorSession.CreateWholeSceneUndoSnapshot()
   at Sandbox.Helpers.UndoSystem.Insert(String title, Action undo, Action redo) in C:\build\_work\sbox\sbox\engine\Sandbox.Tools\Utility\UndoSystem.cs:line 102
   at Editor.SceneEditorSession.PushUndoSelection() in C:\build\_work\sbox\sbox\engine\Sandbox.Tools\Scene\Session\SceneEditorSession.Undo.cs:line 119
   at Editor.SceneTreeWidget.<BuildUI>b__8_2(Object x) in C:\My Stuff\Steam\steamapps\common\sbox\addons\tools\Code\Scene\SceneTree\SceneTree.cs:line 62
   at Editor.BaseItemWidget.SetSelected(Object obj, Boolean state, Boolean skipEvents) in C:\build\_work\sbox\sbox\engine\Sandbox.Tools\Widgets\BaseItemWidget.cs:line 914
   at Editor.TreeView.SetSelected(Object obj, Boolean state, Boolean skipEvents) in C:\My Stuff\Steam\steamapps\common\sbox\addons\tools\Code\Widgets\TreeView\TreeView.cs:line 420
   at Editor.BaseItemWidget.SelectItem(Object obj, Boolean add, Boolean skipEvents) in C:\build\_work\sbox\sbox\engine\Sandbox.Tools\Widgets\BaseItemWidget.cs:line 859
   at Editor.BaseItemWidget.OnMouseReleased(MouseEvent e) in C:\build\_work\sbox\sbox\engine\Sandbox.Tools\Widgets\BaseItemWidget.cs:line 567
   at Managed.SourceTools.Exports.Editor_BaseScrollWidget_InternalMouseReleaseEvent(UInt32 self, IntPtr e) in C:\build\_work\sbox\sbox\engine\Sandbox.Tools\Interop.Tools.cs:line 15804
```

### To Reproduce

1. Open the bug repo I've uploaded
2. Open the test_parent prefab
3. Try and add an action to the test_child prefab variable

### Expected behavior

Should work the same way any other action would

### Media/Files

[bug_repo.zip](https://github.com/user-attachments/files/17712218/bug_repo.zip)

**Comment by Metapyziks** [comment]
Probably the same issue as #6880, but thanks for the extra info!
