### ISSUE TITLE
'Unknown Tool Window" warning whenever you close a scene

### ISSUE THREAD

**Issue by Retroeer** [Facepunch/sbox-issues#6916]
### Describe the bug

Closing a scene gives you a "unknown tool window" warning, this doesn't do anything, but its just slightly annoying, here's the full error

```
unknown tool window
   at Sandbox.EngineLoop.Print(Int32 severity, String logger, String message) in C:\build\_work\sbox\sbox\engine\Sandbox.Engine\EngineLoop.cs:line 340
   at Managed.SandboxEngine.Exports.Sandbox_EngineLoop_Print(Int32 severitty, IntPtr logger, IntPtr message) in C:\build\_work\sbox\sbox\engine\Sandbox.Engine\Interop.Engine.cs:line 12166
   at Sandbox.EngineLoop.RunFrame(CMaterialSystem2AppSystemDict appDict, Boolean& wantsQuit) in C:\build\_work\sbox\sbox\engine\Sandbox.Engine\EngineLoop.cs:line 46
   at Sandbox.AppSystem.Run() in C:\build\_work\sbox\sbox\engine\Sandbox.AppSystem\AppSystem.cs:line 85
   at Sandbox.Launcher.Main() in C:\build\_work\sbox\sbox\engine\Launcher\SboxDev\Launcher.cs:line 24
   at Sandbox.Program.Launch() in C:\build\_work\sbox\sbox\engine\Launcher\Shared\Startup.cs:line 21
   at Sandbox.Program.Main() in C:\build\_work\sbox\sbox\engine\Launcher\Shared\Startup.cs:line 16
```

### To Reproduce

1. Open a Scene
2. Close it

### Expected behavior

There shouldn't be a warning

### Media/Files

https://github.com/user-attachments/assets/7bedd16f-37e6-400d-a437-0601099168af

**Comment by Retroeer** [comment]
sol goodman
