### ISSUE TITLE
`Gizmo.Sprite` doesn't load textures correctly

### ISSUE THREAD

**Issue by Fortune117** [Facepunch/sbox-issues#6919]
### Describe the bug

I have a line:
```CS
Gizmo.Draw.Sprite(Vector3.Up * MapGenerator.SlotSize/6f, 24f, "textures/editor/gizmo_connection.png");
```

it gives an error in console though: 
```
Image.Load: textures/editor/gizmo_connection.png not found (Could not find file `/textures/editor/gizmo_connection.png`.)
   at Sandbox.TextureLoader.Image.Load(BaseFileSystem filesystem, String filename, Boolean warnOnMissing) in C:\build\_work\sbox\sbox\engine\Sandbox.Engine\Resources\Textures\Loader\ImageLoader.cs:line 151
   at Sandbox.Texture.TryToLoad(BaseFileSystem filesystem, String filepath, Boolean warnOnMissing) in C:\build\_work\sbox\sbox\engine\Sandbox.Engine\Resources\Textures\Texture.Load.cs:line 138
   at Sandbox.Texture.Load(BaseFileSystem filesystem, String filepath, Boolean warnOnMissing) in C:\build\_work\sbox\sbox\engine\Sandbox.Engine\Resources\Textures\Texture.Load.cs:line 42
   at Sandbox.Gizmo.GizmoDraw.Sprite(Vector3 center, Single size, String texture) in C:\build\_work\sbox\sbox\engine\Sandbox.Engine\Gizmos\Draw\Draw.Solid.cs:line 526
   at DMD<System.Void DarkDescent.LevelGeneration.Components.MapModuleComponent:DrawConnection(Vector3, DarkDescent.LevelGeneration.Faces.FaceConnectionResource, DarkDescent.LevelGeneration.Components.MapModuleComponent+ConnectionDirection)>(MapModuleComponent this, Vector3 offset, FaceConnectionResource resource, ConnectionDirection direction)
   at DarkDescent.LevelGeneration.Components.MapModuleComponent.DrawSubmodule(PrototypeSubmodule submodule) in C:\My Stuff\Steam\steamapps\common\sbox\addons\dark_descent\Code\dungeon\components\MapModuleComponent.cs:line 57
   at DarkDescent.LevelGeneration.Components.MapModuleComponent.DrawSubmodules() in C:\My Stuff\Steam\steamapps\common\sbox\addons\dark_descent\Code\dungeon\components\MapModuleComponent.cs:line 35
   at DarkDescent.LevelGeneration.Components.MapModuleComponent.DrawGizmos() in C:\My Stuff\Steam\steamapps\common\sbox\addons\dark_descent\Code\dungeon\components\MapModuleComponent.cs:line 25
   at Sandbox.GameObject.<>c__DisplayClass122_0.<DrawGizmos>b__0(Component c) in C:\build\_work\sbox\sbox\engine\Sandbox.Game\Scene\GameObject\GameObject.Gizmo.cs:line 150
   at Sandbox.ComponentList.ForEach[T](String name, Boolean includeDisabled, Action`1 action) in C:\build\_work\sbox\sbox\engine\Sandbox.Game\Scene\GameObject\ComponentList.cs:line 293
   at Sandbox.GameObject.DrawGizmos() in C:\build\_work\sbox\sbox\engine\Sandbox.Game\Scene\GameObject\GameObject.Gizmo.cs:line 147
   at Sandbox.Scene.EditorDraw(Boolean drawGizmos) in C:\build\_work\sbox\sbox\engine\Sandbox.Game\Scene\Scene\Scene.Tick.cs:line 113
   at Editor.SceneViewportWidget.Frame(Boolean isActive) in C:\My Stuff\Steam\steamapps\common\sbox\addons\tools\Code\Scene\SceneView\SceneViewportWidget.cs:line 335
   at Editor.SceneViewWidget.Frame() in C:\My Stuff\Steam\steamapps\common\sbox\addons\tools\Code\Scene\SceneView\SceneViewWidget.cs:line 106
   at InvokeStub_SceneViewWidget.Frame(Object, Object, IntPtr*)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Sandbox.Internal.EventSystem.<>c__DisplayClass11_0.<BuildDelegate>b__0(Object o, Object[] p) in C:\build\_work\sbox\sbox\engine\Sandbox.Event\EventSystem.cs:line 236
   at Sandbox.Internal.EventSystem.EventAction.Run(String name, Object[] args) in C:\build\_work\sbox\sbox\engine\Sandbox.Event\EventSystem.cs:line 89
   at Sandbox.Internal.EventSystem.EventList.Run(String name, Object[] args) in C:\build\_work\sbox\sbox\engine\Sandbox.Event\EventSystem.cs:line 124
   at Sandbox.Internal.EventSystem.Run(String v) in C:\build\_work\sbox\sbox\engine\Sandbox.Event\EventSystem.cs:line 344
   at Editor.ManagedTools.RunFrame() in C:\build\_work\sbox\sbox\engine\Sandbox.Tools\ManagedTools.cs:line 115
   at Managed.SourceTools.Exports.Editor_ManagedTools_RunFrame() in C:\build\_work\sbox\sbox\engine\Sandbox.Tools\Interop.Tools.cs:line 20336
   at Sandbox.EngineLoop.RunFrame(CMaterialSystem2AppSystemDict appDict, Boolean& wantsQuit) in C:\build\_work\sbox\sbox\engine\Sandbox.Engine\EngineLoop.cs:line 46
   at Sandbox.AppSystem.Run() in C:\build\_work\sbox\sbox\engine\Sandbox.AppSystem\AppSystem.cs:line 85
   at Sandbox.Launcher.Main() in C:\build\_work\sbox\sbox\engine\Launcher\SboxDev\Launcher.cs:line 24
   at Sandbox.Program.Launch() in C:\build\_work\sbox\sbox\engine\Launcher\Shared\Startup.cs:line 21
   at Sandbox.Program.Main() in C:\build\_work\sbox\sbox\engine\Launcher\Shared\Startup.cs:line 16
```

The file definitely exists though.

### To Reproduce

1. Open the attached repo
2. Look at the editor
3. See error

### Expected behavior

Should load textures correctly.

### Media/Files

[bug_repo.zip](https://github.com/user-attachments/files/17743333/bug_repo.zip)

**Comment by Fortune117** [comment]
notably this works:
```CS
Gizmo.Draw.Sprite(Vector3.Up * MapGenerator.SlotSize/6f, 24f, Texture.Load(FileSystem.Mounted,"textures/editor/gizmo_connection.png"));
```

**Comment by aylaylay** [comment]
That is the function you're meant to use, the function not providing the filesystem uses the engine filesystem which is files from core, base, citizen. Loading texture from mounted is what you're meant to do. As far as I'm aware this isn't going to change.
