### ISSUE TITLE
Lobby is toxic error, lobby crashes

### ISSUE THREAD

**Issue by ceitine** [Facepunch/sbox-issues#6943]
### Describe the bug

We were playtesting Shoot and Build with around 30 people in one lobby.
Sometimes lobbies would just freeze for a bit, give everyone blackscreens and eventually throw everyone into the s&box menu.

This is one of the errors that came up:
```
[Generic] Disconnecting - Lobby is toxic
   at Sandbox.Network.SteamLobbySocket.Sandbox.ILobby.OnLobbyUpdated() in C:\build_work\sbox\sbox\engine\Sandbox.Engine\Networking\Transports\SteamLobby\SteamLobbySocket.cs:line 354
   at Sandbox.LobbyManager.OnDataUpdate(UInt64 lobbyid, UInt64 targetid) in C:\build_work\sbox\sbox\engine\Sandbox.Engine\Game\Lobby\LobbyManager.cs:line 45
   at Managed.SandboxEngine.Exports.Sandbox_LobbyManager_OnDataUpdate(UInt64 lobbyid, UInt64 targetid) in C:\build_work\sbox\sbox\engine\Sandbox.Engine\Interop.Engine.cs:line 12359
   at Sandbox.EngineLoop.FrameStart() in C:\build_work\sbox\sbox\engine\Sandbox.Engine\EngineLoop.cs:line 121
   at Sandbox.EngineLoop.RunFrame(CMaterialSystem2AppSystemDict appDict, Boolean& wantsQuit) in C:\build_work\sbox\sbox\engine\Sandbox.Engine\EngineLoop.cs:line 36
   at Sandbox.AppSystem.Run() in C:\build_work\sbox\sbox\engine\Sandbox.AppSystem\AppSystem.cs:line 85
   at Sandbox.Launcher.Main() in C:\build_work\sbox\sbox\engine\Launcher\Sbox\Launcher.cs:line 8
   at Sandbox.Program.Launch() in C:\build_work\sbox\sbox\engine\Launcher\Shared\Startup.cs:line 21
   at Sandbox.Program.Main() in C:\build_work\sbox\sbox\engine\Launcher\Shared\Startup.cs:line 16
```

### To Reproduce

Honestly, no clue..

### Expected behavior

Well ideally, if we're doing something wrong, I'd like the error to tell me what the issue is.

### Media/Files

![Image](https://github.com/user-attachments/assets/eeb0c1c5-a9ed-4977-ae15-bc6770aedcc0)
![Image](https://github.com/user-attachments/assets/591d7f3c-7bf8-47d7-9aa4-a2292877fa40)
![Image](https://github.com/user-attachments/assets/ac83b35e-65a9-40cb-bb8e-717ffa52155f)

**Comment by ceitine** [comment]
here's my full log from the playtest, it's a little long!
[sbox.41.log](https://github.com/user-attachments/files/17805800/sbox.41.log)

**Comment by ceitine** [comment]
this probably doesn't apply anymore, i think conna has more recent networking issues from our playtests
