### ISSUE TITLE
NRE Error when joining a dedicated server in s&box editor

### ISSUE THREAD

**Issue by PolSpock** [Facepunch/sbox-issues#6956]
### Describe the bug

Hi,

If you create a dedicated server for your game and try to join it through the S&box editor, you will encounter an NullReferenceException:
```
Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Sandbox.Scene.PreCameraRender() in C:\build\_work\sbox\sbox\engine\Sandbox.Game\Scene\Scene\Scene.cs:line 209
   at Sandbox.Scene.Render() in C:\build\_work\sbox\sbox\engine\Sandbox.Game\Scene\Scene\Scene.cs:line 174
   at Sandbox.EngineLoop.OnClientOutput() in C:\build\_work\sbox\sbox\engine\Sandbox.Engine\EngineLoop.cs:line 414
   at Managed.SandboxEngine.Exports.Sandbox_EngineLoop_OnClientOutput() in C:\build\_work\sbox\sbox\engine\Sandbox.Engine\Interop.Engine.cs:line 12198
```

### To Reproduce

1) Push your game to asset.party
2) Create a dedicated server using the following command :
`.\sbox-server.exe +game myorg.mygame myorg.mygame_dedicated_server_scene`
3) Join the dedicated server with your S&box dev editor ; you’ll encounter the spammy error shown above
Additionally, you might encounter many other errors, but that’s not the topic here.

### Expected behavior

No error

### Media/Files

https://github.com/user-attachments/assets/ee8f7967-92d5-4153-baed-0fa7110bf975

**Comment by DevulTj** [comment]
Does this still happen? I can't repro it.

**Comment by PolSpock** [comment]
Yep, seems fixed
