### ISSUE TITLE
Rpcs are broken

### ISSUE THREAD

**Issue by Nolankicks** [Facepunch/sbox-issues#7084]
### Describe the bug

They don't get called at all. Many issues. NRE's are called.

### To Reproduce

Play any game.

### Expected behavior

Should not be broken

**Comment by MrBrax** [comment]
getting weird stuff too unless i upgraded wrong

```
[Generic] Object reference not set to an instance of an object.	System.NullReferenceException: Object reference not set to an instance of an object.
   at Sandbox.Rpc.get_CallerId() in C:\build\_work\sbox\sbox\engine\Sandbox.Game\Scene\Networking\Rpc.cs:line 100
   at Sandbox.Rpc.HasInstancePermission(GameObject go, NetFlags permission) in C:\build\_work\sbox\sbox\engine\Sandbox.Game\Scene\Networking\Rpc.InstanceRpc.cs:line 102
   at Sandbox.Rpc.OnCallInstanceRpc(GameObject& go, Component& component, WrappedMethod& m, Object[]& argumentList) in C:\build\_work\sbox\sbox\engine\Sandbox.Game\Scene\Networking\Rpc.InstanceRpc.cs:line 133
   at Braxnet.Player.PlayerCarry.SetActiveCarriable(BaseCarriable carriable) in C:\Users\Braxen\Documents\S&box Projects\braxnet\Code\Player\PlayerCarry.cs:line 81```

**Comment by Nolankicks** [comment]
Seems like authority rpcs don't work at all

**Comment by SpiltBeanz** [comment]
Same here. Game completely stopped working moments before our scheduled play test. EXTREMELY inconvenient. :(

**Comment by Nolankicks** [comment]
Rpc.Host is still broken

**Comment by Nolankicks** [comment]
Rpc.Owner is broken

**Comment by kurozael** [comment]
Sorted, re-open if you experience other issues.
