### ISSUE TITLE
Newly created custom asset can't be inspected

### ISSUE THREAD

**Issue by MrBrax** [Facepunch/sbox-issues#7112]
### Describe the bug

Sometimes when creating an asset, it will give errors in the console and a blank inspector. This started happening after the new asset browser.

Restarting fixes it, but just seemingly randomly when creating a new asset, it happens.

### To Reproduce

1. Create custom asset
2. Sometimes it will error

### Expected behavior

Work normally

### Media/Files

```
2024/12/04 16:53:28.2720	[GameMenu] Tried to load items/misc/power_strip/new item data.item but couldn't get compiled file	
2024/12/04 16:53:34.6251	[engine/AssetSystem] Cannot recompile 'items/misc/power_strip/new item data.item': Source file not present.	
2024/12/04 16:53:34.6251	[GameMenu] Detected Added File /items/misc/power_strip/power_strip.item_c	
2024/12/04 16:53:34.6251	[GameMenu] [GameMenu] Detected Asset File Deleted /items/misc/power_strip/new item data.item_c	
2024/12/04 16:53:35.9568	[Interop] Exception has been thrown by the target of an invocation.	System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Exception: Can't serialize object type 'Braxnet.Data.ItemData'
   at Sandbox.Internal.TypeLibrary.GetSerializedObject(Object target) in C:\build\_work\sbox\sbox\engine\Sandbox.Reflection\TypeLibrary\TypeLibrary.cs:line 526
   at Editor.Inspectors.AssetInspector.CreateContentUI(Asset target, AssetPreview preview) in C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\tools\Code\Inspectors\AssetInspector.cs:line 239
   at Editor.Inspectors.AssetInspector.RebuildUI() in C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\tools\Code\Inspectors\AssetInspector.cs:line 128
   at Editor.Inspectors.AssetInspector..ctor(SerializedObject so) in C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\tools\Code\Inspectors\AssetInspector.cs:line 71
   at InvokeStub_AssetInspector..ctor(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at Editor.InspectorWidget.Create(SerializedObject obj)
   at Editor.Inspector.StartInspecting(Object obj, Boolean addToHistory) in C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\tools\Code\Editor\Inspector.cs:line 69
   at Editor.Inspector.StartInspecting(Object target) in C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\tools\Code\Editor\Inspector.cs:line 30
   at Editor.EditorUtility.set_InspectorObject(Object value) in C:\build\_work\sbox\sbox\engine\Sandbox.Tools\Utility\Utility.cs:line 37
   at Editor.MainAssetBrowser.<>c.<.ctor>b__4_0(Asset a) in C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\tools\Code\Editor\AssetBrowser\MainAssetBrowser.cs:line 24
   at Editor.AssetBrowser.<.ctor>b__48_0(Object o) in C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\tools\Code\Editor\AssetBrowser\AssetBrowser.cs:line 166
   at Editor.AssetList.<.ctor>b__35_0(Object a) in C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\tools\Code\Editor\AssetList\AssetList.cs:line 38
   at Editor.BaseItemWidget.SetSelected(Object obj, Boolean state, Boolean skipEvents)
   at Editor.BaseItemWidget.OnMouseReleased(MouseEvent e) in C:\build\_work\sbox\sbox\engine\Sandbox.Tools\Widgets\BaseItemWidget.cs:line 562
   at Managed.SourceTools.Exports.Editor_BaseScrollWidget_InternalMouseReleaseEvent(UInt32 self, IntPtr e) in C:\build\_work\sbox\sbox\engine\Sandbox.Tools\Interop.Tools.cs:line 15807
```

**Comment by CarsonKompon** [comment]
This seems to be working for me as of Sol's most recent commits, can you confirm?

**Comment by MrBrax** [comment]
it hasn't errored for me yet, i'll continue testing for a bit

**Comment by MrBrax** [comment]
seems good so far!
