### ISSUE TITLE
returning error texture ressource for "" in CTextureManagerVk::GetTextureRessource

### ISSUE THREAD

**Issue by EternalDawn1** [Facepunch/sbox-issues#7148]
### Describe the bug

returning error texture resource for "" in CTextureManagerVK::GetTextureResource
   at Sandbox.EngineLoop.Print(Int32 severity, String logger, String message) in C:\build\_work\sbox\sbox\engine\Sandbox.Engine\EngineLoop.cs:line 335
   at Managed.SandboxEngine.Exports.Sandbox_EngineLoop_Print(Int32 severitty, IntPtr logger, IntPtr message) in C:\build\_work\sbox\sbox\engine\Sandbox.Engine\Interop.Engine.cs:line 12221

### To Reproduce

when creating an object with the block-tool its look like picture (2)

### Expected behavior

? not errory 🌵 

### Media/Files

![Image](https://github.com/user-attachments/assets/3ce01d08-b746-4a05-adff-1f35ced8d82b)
![Image](https://github.com/user-attachments/assets/db62fa66-d4c2-40ac-92ab-af5d40e5404d)

### Additional context

i tried to unistall sbox , but nothing helped , even search for local files to be broken ...

**Comment by EternalDawn1** [comment]
reinstall and delete all sbox core files helped
