### ISSUE TITLE
[Editor] Exception when you add a TreeNode.Spacer node to a TreeNode.

### ISSUE THREAD

**Issue by badandbest** [Facepunch/sbox-issues#7155]
### Describe the bug

When you add a TreeNode.Spacer to a TreeNode it throws an exception and doesn't create any children.

### To Reproduce

1. Create a TreeNode.Spacer node.
2. Add the spacer to any TreeNode.

```c#
var spacer = new TreeNode.Spacer( 17 );

treeNode.AddItem( spacer );
``` 

### Expected behavior

TreeNode.Spacer should not cause the tree to throw exceptions.

### Media/Files

```
Value cannot be null. (Parameter 'key')
System.ArgumentNullException: Value cannot be null. (Parameter 'key')
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Linq.Enumerable.SpanToDictionary[TSource,TKey,TElement](ReadOnlySpan`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at Editor.TreeNode.SetChildren[T](IEnumerable`1 list, Func`2 createNode) in C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\tools\Code\Widgets\TreeView\TreeNode.cs:line 382
   at Editor.SceneNode.BuildChildren() in C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\tools\Code\Scene\SceneTree\SceneNode.cs:line 13
   at Editor.TreeNode.OnHashChanged() in C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\tools\Code\Widgets\TreeView\TreeNode.cs:line 368
   at Editor.TreeNode.UpdateHash() in C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\tools\Code\Widgets\TreeView\TreeNode.cs:line 359
   at Editor.TreeView.GetItemHasChildren(Object obj) in C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\tools\Code\Widgets\TreeView\TreeView.cs:line 78
   at Editor.TreeView.RecursiveLayout(Object item, LayoutConfig& config) in C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\tools\Code\Widgets\TreeView\TreeView.cs:line 183
   at Editor.TreeView.BuildLayout(LayoutConfig& config) in C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\tools\Code\Widgets\TreeView\TreeView.cs:line 165
   at Editor.TreeView.LayoutScrollbar() in C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\tools\Code\Widgets\TreeView\TreeView.cs:line 134
   at Editor.TreeView.Rebuild() in C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\tools\Code\Widgets\TreeView\TreeView.cs:line 110
   at Managed.SourceTools.Exports.Editor_BaseScrollWidget_InternalOnResizeEvent(UInt32 self, IntPtr e) in C:\build\_work\sbox\sbox\engine\Sandbox.Tools\Interop.Tools.cs:line 15988

``` 

```
Error calling event 'tool.frame' on 'Editor.TreeView'
System.ArgumentNullException: Value cannot be null. (Parameter 'key')
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Linq.Enumerable.SpanToDictionary[TSource,TKey,TElement](ReadOnlySpan`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at Editor.TreeNode.SetChildren[T](IEnumerable`1 list, Func`2 createNode) in C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\tools\Code\Widgets\TreeView\TreeNode.cs:line 382
   at Editor.SceneNode.BuildChildren() in C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\tools\Code\Scene\SceneTree\SceneNode.cs:line 13
   at Editor.TreeNode.RebuildOnDirty() in C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\tools\Code\Widgets\TreeView\TreeNode.cs:line 152
   at Editor.TreeNode.Think() in C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\tools\Code\Widgets\TreeView\TreeNode.cs:line 146
   at Editor.TreeNode.ThinkInternal() in C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\tools\Code\Widgets\TreeView\TreeNode.cs:line 131
   at Editor.TreeView.Frame() in C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\tools\Code\Widgets\TreeView\TreeView.cs:line 776
   at InvokeStub_TreeView.Frame(Object, Object, IntPtr*)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)

``` 

### Additional context

The same thing happens with TreeNode.Header, TreeNode.SmallHeader and TreeNode.Section.

**Comment by aylaylay** [comment]
do you have a full example?

**Comment by aylaylay** [comment]
works fine for me so i'll need a full example

**Comment by badandbest** [comment]
It still works for me. In SceneTreeView, try adding this after creating the SceneNode:

```c#
node.AddItem( new TreeNode.Spacer( 17 ) );
``` 

![Image](https://github.com/user-attachments/assets/875420c3-af38-4ad0-a252-2c5ddf303130)

**Comment by aylaylay** [comment]
Fixed
