### ISSUE TITLE
Dropped assets/objects on empty/full lists should add it anyway

### ISSUE THREAD

**Issue by MrBrax** [Facepunch/sbox-issues#7197]
### What can't you do?

When dragging for example a sound file into "Sounds" in a sound event, it doesn't accept it until you add an empty slot for it. Often times i forget to do that, doing the motion twice.

https://github.com/user-attachments/assets/3d5c7ebf-de88-46c9-9c70-666468d6b259

### How would you like it to work?

Should probably show that you can drop the object on it and when you release it should append it

### What have you tried?

Dragging

**Comment by MrBrax** [comment]
I think it broke, dropping a sound file on a sound event source list.

```
Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Editor.ListControlWidget.ListControlAddButton.OnDragDrop(DragEvent ev) in C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\tools\Code\Widgets\ControlWidgets\ListControlWidget.cs:line 510
   at Editor.Widget.InternalDropEvent(QDropEvent e) in C:\build\_work\sbox\sbox\engine\Sandbox.Tools\Qt\Widget.Events.cs:line 648
   at Managed.SourceTools.Exports.Editor_Widget_InternalDropEvent(UInt32 self, IntPtr e) in C:\build\_work\sbox\sbox\engine\Sandbox.Tools\Interop.Tools.cs:line 22952
```

**Comment by CarsonKompon** [comment]
Will push something shortly that should fix it
