### ISSUE TITLE
[Asset Browser] Opening everything tab does not work

### ISSUE THREAD

**Issue by Nolankicks** [Facepunch/sbox-issues#7199]
### Describe the bug

Opening everything tab does not work

### To Reproduce

Open the everything tab

### Expected behavior

It should work

### Media/Files

https://github.com/user-attachments/assets/ed8c37ce-39e7-4d7c-8a62-f38e7867a331

NRE:
Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Editor.PathWidget.UpdateSegments() in C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\tools\Code\Editor\AssetBrowser\PathWidget.cs:line 82
   at Editor.AssetBrowser.UpdateAssetList() in C:\Program Files (x86)\Steam\steamapps\common\sbox\addons\tools\Code\Editor\AssetBrowser\AssetBrowser.cs:line 341
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Sandbox.Tasks.ExpirableSynchronizationContext.ProcessQueue() in C:\build\_work\sbox\sbox\engine\Sandbox.Engine\Threads\ExpirableSynchronizationContext.cs:line 389

**Comment by aylaylay** [comment]
It looks like it takes some time to populate, have you tried waiting? I've fixed the NRE though I wasn't getting it myself

**Comment by Nolankicks** [comment]
Yeah, I've had it open for about 5 mins

**Comment by Nolankicks** [comment]
No Sol added it @Retroeer

**Comment by solwllms** [comment]
Yeah it should be working fine, can take a moment to populate but it's still pretty fast.
Has the NRE fix not sorted this? Are you getting any other errors or have any idea of a repro?

**Comment by Nolankicks** [comment]
Yeah it seems to be working for me last night. Thanks!
