### ISSUE TITLE
Can't pass custom razor elements as ChildContent to other custom razor elements

### ISSUE THREAD

**Issue by trundlr** [Facepunch/sbox-issues#7203]
### Describe the bug

It's impossible to pass a razor element as ChildContent for another custom razor element (non-builtin) as far as I can tell.

![Image](https://github.com/user-attachments/assets/114c21b9-5fa3-45a0-b9a0-59b37d7488f9)

```
Error | 'SelectionMenu' does not contain a definition for 'SelectionMenuTitle' and no accessible extension method 'SelectionMenuTitle' accepting a first argument of type 'SelectionMenu' could be found (are you missing a using directive or an assembly reference?) - _gen_FloorSelectionMenu.razor_3c355040.cs:28,76
   at Sandbox.CompileGroup.BuildAsync()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
   at Sandbox.Tasks.ExpirableSynchronizationContext.ProcessQueue() in 
```

```
'SelectionMenu' does not contain a definition for 'SelectionMenuTitle' and no accessible extension method 'SelectionMenuTitle' accepting a first argument of type 'SelectionMenu' could be found (are you missing a using directive or an assembly reference?)
at 'SelectionMenu' does not contain a definition for 'SelectionMenuTitle' and no accessible extension method 'SelectionMenuTitle' accepting a first argument of type 'SelectionMenu' could be found (are you missing a using directive or an assembly reference?) in UI/SelectionMenus/FloorSelectionMenu.razor:line 6
```

### To Reproduce

See above!

### Expected behavior

We should be able to pass custom panels as children into custom panels. It is very common practice in web development.

**Comment by trundlr** [comment]
Ok apparently it works if there are only lowercased letters in the element name and attributes 🤣 
![Image](https://github.com/user-attachments/assets/1582b603-d6bd-4203-893d-90698f5556ac)

**Comment by solwllms** [comment]
You need to expliclty specify which RenderFragment the stuff goes inside of (you can do multiple in a panel, at whatever points you like), so something like this should work:

```
<SelectionMenu>
	<ChildContent>
		<SelectionMenuTitle Title="Balls" />
	</ChildContent>
</SelectionMenu>

```

Does blazor do that implicitly if it's just ChildContent? im not even sure how that would work

**Comment by trundlr** [comment]
I'm not sure about Blazor - but if it works all lowercased without nesting in <ChildContent> tags, shouldn't it just work for upper cased as well? It's incredibly common to slot children in like how I have above in web frameworks, without having to specify some child tag.

**Comment by trundlr** [comment]
https://blazor-university.com/templating-components-with-renderfragements/

This seems to imply you only need ChildContent if there is more than one RenderFragment being used on a component.
