### ISSUE TITLE
Can't Join via New Instance with too much code

### ISSUE THREAD

**Issue by rileyzzz** [Facepunch/sbox-issues#7250]
### Describe the bug

When trying to join my game via a local instance in the editor, I get the following errors in the client:
```
2024/12/25 05:28:02.4573	[Generic] Trying to read array with too many elements	System.IndexOutOfRangeException: Trying to read array with too many elements
   at Sandbox.ByteStream.ReadArray[T](Int32 maxElements) in C:\build\_work\sbox\sbox\engine\Sandbox.System\Utility\ByteStream\ByteStream.cs:line 430
   at Sandbox.Network.StringTable.ReadSnapshot(ByteStream bs) in C:\build\_work\sbox\sbox\engine\Sandbox.Engine\Networking\Tables\StringTable.cs:line 139
   at Sandbox.Network.NetworkSystem.TableMessage(InternalMessageType type, NetworkMessage msg) in C:\build\_work\sbox\sbox\engine\Sandbox.Engine\Networking\System\NetworkSystem.Tables.cs:line 49
   at Sandbox.Network.NetworkSystem.HandleIncomingMessage(NetworkMessage msg) in C:\build\_work\sbox\sbox\engine\Sandbox.Engine\Networking\System\NetworkSystem.Message.cs:line 241
2024/12/25 05:28:02.4573	[Generic] TODO: Disconnect on error (Trying to read array with too many elements)
```

after which point none of the gameplay code works on the client.

### To Reproduce

I don't have a list of solid repro steps (could be made trickier to reproduce if codearchives are compressed etc) but after debugging it seems like the size of my code is to blame, it looks like when `Sandbox.Network.StringTable.ReadSnapshot` is trying to read the 'CodeArchive' bytestream but it's exceeding the max element count.
Looking at the decompiled source of ReadSnapshot, it looks like the current cap is around ~4mb. My C# exceeds this limit by a significant amount, and I could foresee projects in the future which use a lot of libraries going beyond this limit pretty easily.

### Expected behavior

Ideally it should just download the codearchive and let me play. This is only an issue in the editor and doesn't affect the actual client when I've uploaded to sbox.game, so hopefully it's an easy fix, but right now this is blocking me from testing multiplayer in my techjam project. If there has to be a limit on the download size, I'd prefer it be really generous as this is only affecting local testing.

**Comment by kurozael** [comment]
This has been increased from 4mb to 8mb - let us know if this is still causing issues.
